import type { GameMap } from '../types';

export const bloomrest: GameMap = {
  id: 'bloomrest',
  name: 'Bloomrest',
  indoor: false,
  tiles: [
    'TTTTTTTTT,,TTTTTTTTTTT',
    'T....................T',
    'T..RRRR...RRRR.RRRR..T',
    'T..RRRR...RRRR.RRRR..T',
    'T..BDBB...BBDB.BBDB..T',
    'T....................T',
    'T.......RRRRRR.......T',
    'T.......RRRRRR.......T',
    'T.......BBBDBB.......T',
    'T.........S..........T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T...............S....T',
    'T....................T',
    'T....................T',
    'T....................T',
    'TTTTTTTTT,,TTTTTTTTTTT',
  ],
  warps: [
    { x: 4, y: 4, to: 'center_bloomrest', tx: 6, ty: 5 },
    { x: 12, y: 4, to: 'mart_bloomrest', tx: 6, ty: 5 },
    { x: 11, y: 8, to: 'gym5', tx: 6, ty: 11 },
    { x: 17, y: 4, to: 'greenhouse', tx: 7, ty: 12 },
    { x: 9, y: 19, to: 'route5', tx: 8, ty: 22 },
    { x: 10, y: 19, to: 'route5', tx: 9, ty: 22 },
    { x: 9, y: 0, to: 'route6', tx: 8, ty: 22 },
    { x: 10, y: 0, to: 'route6', tx: 9, ty: 22 },
  ],
  npcs: [
    {
      id: 'bloomrest_npc1',
      x: 6,
      y: 11,
      spriteKey: 'villager1',
      facing: 'down',
      dialogue: [
        'The greenhouse grows berries year-round. The farmer trades them for other goods.',
      ],
    },
    {
      id: 'bloomrest_npc2',
      x: 15,
      y: 12,
      spriteKey: 'villager2',
      facing: 'left',
      dialogue: [
        'Leader Fern treats every battle like tending a garden. Patience and precision.',
      ],
    },
    {
      id: 'bloomrest_npc3',
      x: 8,
      y: 14,
      spriteKey: 'professor',
      facing: 'down',
      dialogue: [
        'The soil here is remarkably fertile. Grass types grow stronger in Bloomrest.',
      ],
    },
    {
      id: 'bloomrest_npc4',
      x: 14,
      y: 6,
      spriteKey: 'lass',
      facing: 'left',
      dialogue: [
        'The Gym is a literal hedge maze. I got lost three times before I found the leader!',
      ],
    },
  ],
  items: [],
  encounters: [],
  encounterRate: 0,
  signs: [
    { x: 10, y: 9, text: 'BLOOMREST - Gym Leader Fern tends the garden of battle.' },
    { x: 15, y: 15, text: 'BLOOMREST GREENHOUSE - Berries and rare plants cultivated here.' },
  ],
  lockedDoors: [],
};
