import type { GameMap } from '../types';

export const cinderwake: GameMap = {
  id: 'cinderwake',
  name: 'Cinderwake',
  indoor: false,
  tiles: [
    'TTTTTTTTT,,TTTTTTTTTTT',
    'T....................T',
    'T..RRRR...RRRR.RRRR..T',
    'T..RRRR...RRRR.RRRR..T',
    'T..BDBB...BBDB.BBDB..T',
    'T..................S.T',
    'T.......RRRRRR.......T',
    'T.......RRRRRR.......T',
    'T.......BBBDBB.......T',
    'T.........S..........T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'TTTTTTTTT,,TTTTTTTTTTT',
  ],
  warps: [
    { x: 4, y: 4, to: 'center_cinderwake', tx: 6, ty: 5 },
    { x: 12, y: 4, to: 'mart_cinderwake', tx: 6, ty: 5 },
    { x: 11, y: 8, to: 'gym6', tx: 6, ty: 11 },
    { x: 17, y: 4, to: 'lavatube', tx: 9, ty: 20 },
    { x: 9, y: 19, to: 'route6', tx: 8, ty: 22 },
    { x: 10, y: 19, to: 'route6', tx: 9, ty: 22 },
    { x: 9, y: 0, to: 'route7', tx: 8, ty: 22 },
    { x: 10, y: 0, to: 'route7', tx: 9, ty: 22 },
  ],
  npcs: [
    {
      id: 'cinder_forge_npc',
      x: 6,
      y: 12,
      spriteKey: 'hiker',
      facing: 'down',
      script: 'cinder_forge',
      dialogue: [],
    },
    {
      id: 'cinder_tip1',
      x: 15,
      y: 10,
      spriteKey: 'villager1',
      facing: 'left',
      dialogue: [
        'The forge never sleeps. We trade held items for the right embers.',
      ],
    },
    {
      id: 'cinder_tip2',
      x: 3,
      y: 12,
      spriteKey: 'villager2',
      facing: 'right',
      dialogue: [
        "Leader Pyra's lava tiles blink on and off. Count the beat, then run.",
      ],
    },
    {
      id: 'cinder_tip3',
      x: 15,
      y: 15,
      spriteKey: 'lass',
      facing: 'down',
      dialogue: [
        'The Lava Tube? Team Rollback crawled in there muttering about branches.',
        'Something about merging conflicts. Sounds like a headache to me.',
      ],
    },
    {
      id: 'cinder_tip4',
      x: 5,
      y: 16,
      spriteKey: 'villager1',
      facing: 'up',
      dialogue: [
        'Ash falls like snow here. Do not breathe too deeply.',
      ],
    },
  ],
  items: [],
  encounters: [],
  encounterRate: 0,
  signs: [
    { x: 10, y: 9, text: 'CINDERWAKE - Gym: Leader Pyra, the Forge Heart. Ember Badge.' },
    { x: 19, y: 5, text: 'LAVA TUBE - Caution: timed lava flows. Mind the rhythm.' },
  ],
  lockedDoors: [],
};
