import type { GameMap } from '../types';

export const gym: GameMap = {
  id: 'gym',
  name: 'Verdant Gym',
  indoor: true,
  tiles: [
    'wwwwwwwwwwwwww',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFooFFFFooFFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFooFFFFooFFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFMMFFFFFw',
    'wwwwwwwwwwwwww',
  ],
  warps: [
    { x: 6, y: 12, to: 'verdantcity', tx: 11, ty: 9 },
    { x: 7, y: 12, to: 'verdantcity', tx: 11, ty: 9 },
  ],
  npcs: [
    {
      id: 'trainer_rocco',
      x: 6,
      y: 8,
      spriteKey: 'hiker',
      facing: 'down',
      dialogue: ['Rocco: Terra is waiting. She does not blink. Ever.'],
      trainer: {
        id: 'trainer_rocco',
        name: 'Gym Trainer Rocco',
        spriteKey: 'hiker',
        party: [
          { species: 'pebblit', level: 7 },
          { species: 'pebblit', level: 8 },
        ],
        prize: 320,
        introText: 'Rocco: Before Terra, you must break through ME!',
        defeatText: 'Rocco: Crushed... like gravel...',
        sight: 3,
        ai: 'smart',
      },
    },
    {
      id: 'leader_terra',
      x: 6,
      y: 2,
      spriteKey: 'gymleader',
      facing: 'down',
      action: 'gymleader',
      dialogue: [],
      trainer: {
        id: 'leader_terra',
        name: 'Leader Terra',
        spriteKey: 'gymleader',
        party: [
          { species: 'pebblit', level: 9 },
          { species: 'bouldron', level: 10 },
        ],
        prize: 1500,
        introText:
          'Terra: I am Terra, the Unshakable Stone. My will, like my Mockemon, does not crack. Show me yours!',
        defeatText: 'Terra: ...The stone cracks. Magnificent.',
        sight: 0,
        ai: 'leader',
        potions: 1,
      },
    },
  ],
  items: [],
  encounters: [],
  encounterRate: 0,
  signs: [],
  lockedDoors: [],
};
