import type { GameMap } from '../types';

export const gym2: GameMap = {
  id: 'gym2',
  name: 'Thornbury Gym',
  indoor: true,
  tiles: [
    'wwwwwwwwwwwwww',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFwwwwwwwFFFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFwwwwwwwwwFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFMMFFFFFw',
    'wwwwwwwwwwwwww',
  ],
  warps: [
    { x: 6, y: 12, to: 'thornbury', tx: 11, ty: 9 },
    { x: 7, y: 12, to: 'thornbury', tx: 11, ty: 9 },
  ],
  npcs: [
    {
      id: 'gymtrainer_silk1',
      x: 12,
      y: 9,
      spriteKey: 'bugcatcher',
      facing: 'down',
      dialogue: ['Aide: The silk threads guide you forward. Never backward.'],
      trainer: {
        id: 'gymtrainer_silk1',
        name: 'Silk Aide Tova',
        spriteKey: 'bugcatcher',
        party: [
          { species: 'silkette', level: 15 },
          { species: 'cocoonet', level: 15 },
        ],
        prize: 600,
        introText: 'Tova: Walk the thread as I do. One direction, no retreat!',
        defeatText: 'Tova: You read the pattern faster than I could weave it...',
        sight: 2,
        ai: 'smart',
      },
    },
    {
      id: 'gymtrainer_silk2',
      x: 9,
      y: 1,
      spriteKey: 'lass',
      facing: 'right',
      dialogue: ['Aide: Leader Weave says patience is the strongest thread.'],
      trainer: {
        id: 'gymtrainer_silk2',
        name: 'Silk Aide Ren',
        spriteKey: 'lass',
        party: [
          { species: 'thistling', level: 16 },
          { species: 'silkette', level: 16 },
        ],
        prize: 640,
        introText: 'Ren: The thread ends here for you, challenger!',
        defeatText: 'Ren: Snapped... just like that. Weave awaits.',
        sight: 2,
        ai: 'smart',
      },
    },
    {
      id: 'leader_weave',
      x: 6,
      y: 2,
      spriteKey: 'gymleader',
      facing: 'down',
      action: 'gymleader',
      dialogue: [],
      trainer: {
        id: 'leader_weave',
        name: 'Leader Weave',
        spriteKey: 'gymleader',
        party: [
          { species: 'silkette', level: 15 },
          { species: 'thistling', level: 15 },
          { species: 'lumoth', level: 17 },
        ],
        prize: 2200,
        introText:
          'Weave: Every thread has a direction, challenger. Mine never retreat. Let us see where yours leads.',
        defeatText: 'Weave: Your thread pulled mine undone. The Silk Badge is yours.',
        sight: 0,
        ai: 'leader',
        potions: 1,
      },
    },
  ],
  items: [],
  encounters: [],
  encounterRate: 0,
  signs: [],
  lockedDoors: [],
  oneWay: [
    { x: 7, y: 11, dir: 'right' },
    { x: 8, y: 11, dir: 'right' },
    { x: 9, y: 11, dir: 'right' },
    { x: 10, y: 11, dir: 'right' },
    { x: 11, y: 11, dir: 'right' },
    { x: 12, y: 10, dir: 'up' },
    { x: 12, y: 9, dir: 'up' },
    { x: 12, y: 8, dir: 'up' },
    { x: 12, y: 7, dir: 'up' },
    { x: 12, y: 6, dir: 'up' },
    { x: 12, y: 5, dir: 'up' },
    { x: 12, y: 4, dir: 'up' },
    { x: 12, y: 3, dir: 'up' },
    { x: 11, y: 1, dir: 'left' },
    { x: 10, y: 1, dir: 'left' },
    { x: 9, y: 1, dir: 'left' },
    { x: 8, y: 1, dir: 'left' },
    { x: 7, y: 1, dir: 'left' },
  ],
};
