import type { GameMap } from '../types';

export const gym3: GameMap = {
  id: 'gym3',
  name: 'Tidewell Gym',
  indoor: true,
  tiles: [
    'wwwwwwwwwwwwww',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'www~w~Fwwwwwww',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'www~w~Fwwwwwww',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFMMFFFFFw',
    'wwwwwwwwwwwwww',
  ],
  warps: [
    { x: 6, y: 12, to: 'tidewell', tx: 11, ty: 9 },
    { x: 7, y: 12, to: 'tidewell', tx: 11, ty: 9 },
  ],
  npcs: [
    {
      id: 'gymtrainer_tide1',
      x: 4,
      y: 10,
      spriteKey: 'hiker',
      facing: 'right',
      dialogue: ['Aide: Turn the valves and the water recedes. Find them both!'],
      trainer: {
        id: 'gymtrainer_tide1',
        name: 'Tide Aide Brook',
        spriteKey: 'hiker',
        party: [
          { species: 'krabbet', level: 21 },
          { species: 'coralily', level: 21 },
        ],
        prize: 840,
        introText: 'Brook: The tide obeys those who turn the valves. Battle first!',
        defeatText: 'Brook: Swept away... the valves are yours to turn.',
        sight: 2,
        ai: 'smart',
      },
    },
    {
      id: 'gymtrainer_tide2',
      x: 9,
      y: 10,
      spriteKey: 'lass',
      facing: 'left',
      dialogue: ['Aide: Leader Nerin says water always finds a way through.'],
      trainer: {
        id: 'gymtrainer_tide2',
        name: 'Tide Aide Dell',
        spriteKey: 'lass',
        party: [
          { species: 'driftail', level: 22 },
          { species: 'krabbet', level: 22 },
        ],
        prize: 880,
        introText: 'Dell: You will not drift past me! Tide battle!',
        defeatText: 'Dell: Pulled under by your current. Nerin awaits.',
        sight: 2,
        ai: 'smart',
      },
    },
    {
      id: 'leader_nerin',
      x: 6,
      y: 2,
      spriteKey: 'gymleader',
      facing: 'down',
      action: 'gymleader',
      dialogue: [],
      trainer: {
        id: 'leader_nerin',
        name: 'Leader Nerin',
        spriteKey: 'gymleader',
        party: [
          { species: 'coralily', level: 21 },
          { species: 'krabbet', level: 21 },
          { species: 'torrentle', level: 23 },
        ],
        prize: 3000,
        introText:
          'Nerin: The tide rises, the tide falls. Show me your current, challenger!',
        defeatText:
          'Nerin: Your current overpowered my tide. The Tide Badge is yours. Wade well.',
        sight: 0,
        ai: 'leader',
        potions: 2,
      },
    },
  ],
  items: [],
  encounters: [],
  encounterRate: 0,
  signs: [],
  lockedDoors: [],
  // valve_a opens the gate at row 8, valve_b opens the gate at row 5
  gates: [
    {
      x: 6,
      y: 8,
      flag: 'gym3_valve_a',
      text: 'A rusted valve gate. Water still pools behind it.',
    },
    {
      x: 6,
      y: 5,
      flag: 'gym3_valve_b',
      text: 'A second valve gate. The water is draining slowly.',
    },
  ],
  buttons: [
    {
      x: 2,
      y: 10,
      flag: 'gym3_valve_a',
      toggle: false,
      text: 'You turned valve A. A gate groans open somewhere!',
    },
    {
      x: 11,
      y: 10,
      flag: 'gym3_valve_b',
      toggle: false,
      text: 'You turned valve B. The last gate swings wide!',
    },
  ],
};
