import type { GameMap } from '../types';

export const gym4: GameMap = {
  id: 'gym4',
  name: 'Voltmere Gym',
  indoor: true,
  tiles: [
    'wwwwwwwwwwwwww',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wwwwwwFwwwwwww',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wwwwwwFwwwwwww',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFMMFFFFFw',
    'wwwwwwwwwwwwww',
  ],
  warps: [
    { x: 6, y: 12, to: 'voltmere', tx: 11, ty: 9 },
    { x: 7, y: 12, to: 'voltmere', tx: 11, ty: 9 },
  ],
  npcs: [
    {
      id: 'gymtrainer_volt1',
      x: 12,
      y: 9,
      spriteKey: 'bugcatcher',
      facing: 'left',
      dialogue: ['Aide: Flip the switches to open the gates. Dyna waits beyond!'],
      trainer: {
        id: 'gymtrainer_volt1',
        name: 'Volt Aide Spark',
        spriteKey: 'bugcatcher',
        party: [
          { species: 'ampule', level: 27 },
          { species: 'zapwing', level: 27 },
        ],
        prize: 1080,
        introText: 'Spark: You will not flip past me! Lightning battle!',
        defeatText: 'Spark: Shorted out... the switches are yours to flip.',
        sight: 2,
        ai: 'smart',
      },
    },
    {
      id: 'gymtrainer_volt2',
      x: 9,
      y: 1,
      spriteKey: 'lass',
      facing: 'down',
      dialogue: ['Aide: Leader Dyna says a good circuit needs every connection.'],
      trainer: {
        id: 'gymtrainer_volt2',
        name: 'Volt Aide Jolt',
        spriteKey: 'lass',
        party: [
          { species: 'voltkat', level: 28 },
          { species: 'sparkit', level: 28 },
        ],
        prize: 1120,
        introText: 'Jolt: I am the last connection! Let us complete the circuit!',
        defeatText: 'Jolt: Disconnected... Dyna is just beyond the gates.',
        sight: 2,
        ai: 'smart',
      },
    },
    {
      id: 'leader_dyna',
      x: 6,
      y: 2,
      spriteKey: 'gymleader',
      facing: 'down',
      action: 'gymleader',
      dialogue: [],
      trainer: {
        id: 'leader_dyna',
        name: 'Leader Dyna',
        spriteKey: 'gymleader',
        party: [
          { species: 'ampule', level: 28 },
          { species: 'zapwing', level: 28 },
          { species: 'dynabolt', level: 30 },
        ],
        prize: 4200,
        introText: 'Dyna: Let us see if your resolve conducts as well as my team!',
        defeatText: 'Dyna: You short-circuited my plans. The Surge Badge is yours.',
        sight: 0,
        ai: 'leader',
        potions: 2,
      },
    },
  ],
  items: [],
  encounters: [],
  encounterRate: 0,
  signs: [],
  lockedDoors: [],
  gates: [
    {
      x: 6,
      y: 8,
      flag: 'gym4_switch_a',
      text: 'An electric gate hums with power. It needs a switch.',
    },
    {
      x: 6,
      y: 5,
      flag: 'gym4_switch_b',
      text: 'A second electric gate crackles. Find the other switch.',
    },
  ],
  buttons: [
    {
      x: 2,
      y: 10,
      flag: 'gym4_switch_a',
      toggle: false,
      text: 'You flipped switch A. A gate hums open!',
    },
    {
      x: 11,
      y: 10,
      flag: 'gym4_switch_b',
      toggle: false,
      text: 'You flipped switch B. Another gate opens!',
    },
  ],
};
