import type { GameMap } from '../types';

export const gym5: GameMap = {
  id: 'gym5',
  name: 'Bloomrest Gym',
  indoor: true,
  tiles: [
    'wwwwwwwwwwwwww',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wwwwwwwwwwwwFw',
    'wFFFFFFFFFFFFw',
    'wFwwwwwwwwwwww',
    'wFFFFFFFFFFFFw',
    'wwwwwwwwwwwwFw',
    'wFFFFFFFFFFFFw',
    'wFwwwwwwwwwwww',
    'wFFFFFFFFFFFFw',
    'wwwwwwFwwwwwFw',
    'wFFFFFMMFFFFFw',
    'wwwwwwwwwwwwww',
  ],
  warps: [
    { x: 6, y: 12, to: 'bloomrest', tx: 11, ty: 9 },
    { x: 7, y: 12, to: 'bloomrest', tx: 11, ty: 9 },
  ],
  npcs: [
    {
      id: 'gymtrainer_leaf1',
      x: 3,
      y: 8,
      spriteKey: 'lass',
      facing: 'right',
      dialogue: ['Aide: The hedges twist and turn. Can you find the path?'],
      trainer: {
        id: 'gymtrainer_leaf1',
        name: 'Leaf Aide Blossom',
        spriteKey: 'lass',
        party: [
          { species: 'bloomule', level: 32 },
          { species: 'thistling', level: 32 },
        ],
        prize: 1280,
        introText: 'Blossom: The garden is wild! Let us see if you can navigate it!',
        defeatText: 'Blossom: Trimmed neatly... the path continues onward.',
        sight: 2,
        ai: 'smart',
      },
    },
    {
      id: 'gymtrainer_leaf2',
      x: 10,
      y: 4,
      spriteKey: 'bugcatcher',
      facing: 'left',
      dialogue: ['Aide: Leader Fern says even thorns have purpose in the garden.'],
      trainer: {
        id: 'gymtrainer_leaf2',
        name: 'Leaf Aide Thorn',
        spriteKey: 'bugcatcher',
        party: [
          { species: 'cactoss', level: 33 },
          { species: 'silkette', level: 33 },
        ],
        prize: 1320,
        introText: 'Thorn: The thorns guard the path! Battle through me!',
        defeatText: 'Thorn: Pruned back... Fern waits at the garden heart.',
        sight: 2,
        ai: 'smart',
      },
    },
    {
      id: 'leader_fern',
      x: 6,
      y: 2,
      spriteKey: 'gymleader',
      facing: 'down',
      action: 'gymleader',
      dialogue: [],
      trainer: {
        id: 'leader_fern',
        name: 'Leader Fern',
        spriteKey: 'gymleader',
        party: [
          { species: 'bloomule', level: 33 },
          { species: 'cactoss', level: 33 },
          { species: 'bloomule', level: 35 },
        ],
        prize: 4900,
        introText: 'Fern: Every garden has thorns, challenger. Let us see yours.',
        defeatText: 'Fern: You pruned my strategy beautifully. The Bloom Badge is yours.',
        sight: 0,
        ai: 'leader',
        potions: 2,
      },
    },
  ],
  items: [],
  encounters: [],
  encounterRate: 0,
  signs: [],
  lockedDoors: [],
};
