import type { GameMap } from '../types';

export const gym6: GameMap = {
  id: 'gym6',
  name: 'Cinderwake Gym',
  indoor: true,
  tiles: [
    'wwwwwwwwwwwwww',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wxxxxxxxxxxxxw',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wxxxxxxxxxxxxw',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFMMFFFFFw',
    'wwwwwwwwwwwwww',
  ],
  warps: [
    { x: 6, y: 12, to: 'cinderwake', tx: 11, ty: 9 },
    { x: 7, y: 12, to: 'cinderwake', tx: 11, ty: 9 },
  ],
  npcs: [
    {
      id: 'gymtrainer_ember1',
      x: 9,
      y: 6,
      spriteKey: 'hiker',
      facing: 'left',
      dialogue: ['Ember1: The forge roars! Can you match its heat?'],
      trainer: {
        id: 'gymtrainer_ember1',
        name: 'Gym Trainer Ember',
        spriteKey: 'hiker',
        party: [
          { species: 'flarat', level: 37 },
          { species: 'cactoss', level: 37 },
        ],
        prize: 1480,
        introText: 'Ember1: Step into the fire! Only the tempered survive!',
        defeatText: 'Ember1: Quenched! You have some heat in you.',
        sight: 3,
        ai: 'smart',
      },
    },
    {
      id: 'gymtrainer_ember2',
      x: 3,
      y: 10,
      spriteKey: 'lass',
      facing: 'right',
      dialogue: ['Ember2: The lava pulses like a heartbeat. Can you feel it?'],
      trainer: {
        id: 'gymtrainer_ember2',
        name: 'Gym Trainer Cinder',
        spriteKey: 'lass',
        party: [
          { species: 'flarat', level: 37 },
          { species: 'pyrelisk', level: 38 },
        ],
        prize: 1520,
        introText: 'Ember2: Watch the tiles! One mistimed step and you are toast.',
        defeatText: 'Ember2: Toasted. Well played.',
        sight: 3,
        ai: 'smart',
      },
    },
    {
      id: 'gymtrainer_ember3',
      x: 9,
      y: 3,
      spriteKey: 'bugcatcher',
      facing: 'left',
      dialogue: ['Ember3: Pyra is just beyond. The forge awaits its master.'],
      trainer: {
        id: 'gymtrainer_ember3',
        name: 'Gym Trainer Ash',
        spriteKey: 'bugcatcher',
        party: [
          { species: 'pyrelisk', level: 38 },
          { species: 'flarat', level: 37 },
        ],
        prize: 1520,
        introText: 'Ember3: Last flame before the forge heart herself!',
        defeatText: 'Ember3: Snuffed. Go on, then. Pyra is waiting.',
        sight: 3,
        ai: 'smart',
      },
    },
    {
      id: 'leader_pyra',
      x: 6,
      y: 2,
      spriteKey: 'gymleader',
      facing: 'down',
      action: 'gymleader',
      dialogue: [],
      trainer: {
        id: 'leader_pyra',
        name: 'Leader Pyra',
        spriteKey: 'gymleader',
        party: [
          { species: 'flarat', level: 37 },
          { species: 'pyrelisk', level: 38 },
          { species: 'cindrake', level: 39 },
        ],
        prize: 4800,
        introText:
          'Pyra: HA! You crossed my lava on TIMING alone? Good! A forge needs a steady hand and a hotter heart! Let me see if yours burns bright enough!',
        defeatText:
          'Pyra: The forge goes quiet. You did not just cross the fire, you FORGED yourself in it! The Ember Badge is yours, challenger!',
        sight: 0,
        ai: 'leader',
        potions: 2,
      },
    },
  ],
  items: [],
  encounters: [],
  encounterRate: 0,
  signs: [],
  lockedDoors: [],
  lavaPeriod: 120,
};
