import type { GameMap } from '../types';

export const gym7: GameMap = {
  id: 'gym7',
  name: 'Zephyr Heights Gym',
  indoor: true,
  tiles: [
    'wwwwwwwwwwwwww',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'w#######F####w',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'w####F#######w',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFw',
    'wFFFFFMMFFFFFw',
    'wwwwwwwwwwwwww',
  ],
  warps: [
    { x: 6, y: 12, to: 'zephyrheights', tx: 11, ty: 9 },
    { x: 7, y: 12, to: 'zephyrheights', tx: 11, ty: 9 },
  ],
  npcs: [
    {
      id: 'gymtrainer_gale1',
      x: 10,
      y: 6,
      spriteKey: 'lass',
      facing: 'left',
      dialogue: ['Gale1: The wind lanes push you left. Find the gaps!'],
      trainer: {
        id: 'gymtrainer_gale1',
        name: 'Gym Trainer Gale',
        spriteKey: 'lass',
        party: [
          { species: 'gustling', level: 42 },
          { species: 'zapwing', level: 42 },
        ],
        prize: 1680,
        introText: 'Gale1: Feel that breeze? It will sweep you off your feet!',
        defeatText: 'Gale1: Swept away! You read the wind well.',
        sight: 3,
        ai: 'smart',
      },
    },
    {
      id: 'gymtrainer_gale2',
      x: 3,
      y: 9,
      spriteKey: 'bugcatcher',
      facing: 'right',
      dialogue: ['Gale2: Each lane has one safe tile. Can you spot them?'],
      trainer: {
        id: 'gymtrainer_gale2',
        name: 'Gym Trainer Cloud',
        spriteKey: 'bugcatcher',
        party: [
          { species: 'zapwing', level: 42 },
          { species: 'howlette', level: 43 },
        ],
        prize: 1720,
        introText: 'Gale2: Step wrong and the wind sends you packing!',
        defeatText: 'Gale2: Blown back. You found the gaps faster than I did.',
        sight: 3,
        ai: 'smart',
      },
    },
    {
      id: 'gymtrainer_gale3',
      x: 10,
      y: 3,
      spriteKey: 'hiker',
      facing: 'left',
      dialogue: ['Gale3: Aeris is just ahead. She already knows you are here.'],
      trainer: {
        id: 'gymtrainer_gale3',
        name: 'Gym Trainer Storm',
        spriteKey: 'hiker',
        party: [
          { species: 'howlette', level: 43 },
          { species: 'skywyrm', level: 43 },
        ],
        prize: 1720,
        introText: 'Gale3: Last gust before the Sky Dancer herself!',
        defeatText: 'Gale3: Dispersed. Go on. She is waiting.',
        sight: 3,
        ai: 'smart',
      },
    },
    {
      id: 'leader_aeris',
      x: 6,
      y: 2,
      spriteKey: 'gymleader',
      facing: 'down',
      action: 'gymleader',
      dialogue: [],
      trainer: {
        id: 'leader_aeris',
        name: 'Leader Aeris',
        spriteKey: 'gymleader',
        party: [
          { species: 'zapwing', level: 42 },
          { species: 'howlette', level: 43 },
          { species: 'skywyrm', level: 44 },
        ],
        prize: 5400,
        introText:
          'Aeris: Oh, you made it through my little breezes? How adorable! Most challengers get blown right back to the entrance. Let me see if you can dance in the sky as well as you walk through it!',
        defeatText:
          'Aeris: Oh my. You did not just walk through the wind, you rode it! The Gale Badge is yours, darling. And with it, the Wing Whistle. The whole region just got a little smaller for you!',
        sight: 0,
        ai: 'leader',
        potions: 2,
      },
    },
  ],
  items: [],
  encounters: [],
  encounterRate: 0,
  signs: [],
  lockedDoors: [],
  windDir: 'left',
};
