import type { GameMap } from '../types';

export const lavatube: GameMap = {
  id: 'lavatube',
  name: 'Lava Tube',
  indoor: true,
  tiles: [
    'wwwwwwwwwwwwwwwwwwww',
    'wFFFFFFFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wxxxxxxxxxxxxxxxxxxw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wxxxxxxxxxxxxxxxxxxw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wwwwwwwwwwwwwwwwwwww',
  ],
  warps: [
    { x: 9, y: 20, to: 'cinderwake', tx: 17, ty: 5 },
  ],
  npcs: [
    {
      id: 'grunt_lt1',
      x: 12,
      y: 7,
      spriteKey: 'villager2',
      facing: 'left',
      dialogue: ['Grunt: Hot down here! Almost as hot as our merge conflicts.'],
      trainer: {
        id: 'grunt_lt1',
        name: 'Rollback Grunt',
        spriteKey: 'villager2',
        party: [
          { species: 'flarat', level: 36 },
          { species: 'nibblex', level: 36 },
        ],
        prize: 1440,
        introText: 'Grunt: You are not in our changelog! Get lost!',
        defeatText: 'Grunt: Merge failed... retreating to base branch.',
        sight: 4,
      },
    },
    {
      id: 'grunt_lt2',
      x: 5,
      y: 12,
      spriteKey: 'villager2',
      facing: 'right',
      dialogue: ['Grunt: The Ledger fragment is ours. Admin Merge has it.'],
      trainer: {
        id: 'grunt_lt2',
        name: 'Rollback Grunt',
        spriteKey: 'villager2',
        party: [
          { species: 'nibblex', level: 37 },
          { species: 'pyrelisk', level: 37 },
        ],
        prize: 1480,
        introText: 'Grunt: Unauthorised access detected! Initiating conflict resolution!',
        defeatText: 'Grunt: Resolution failed. Pulling back.',
        sight: 4,
      },
    },
    {
      id: 'grunt_lt3',
      x: 13,
      y: 16,
      spriteKey: 'villager2',
      facing: 'left',
      dialogue: ['Grunt: The lava rhythm is easy once you read the patch notes.'],
      trainer: {
        id: 'grunt_lt3',
        name: 'Rollback Grunt',
        spriteKey: 'villager2',
        party: [
          { species: 'pyrelisk', level: 38 },
          { species: 'flarat', level: 38 },
        ],
        prize: 1520,
        introText: 'Grunt: Another unmerged contributor? I will rebase you!',
        defeatText: 'Grunt: Rebased... onto nothing. Ouch.',
        sight: 4,
      },
    },
    {
      id: 'admin_merge',
      x: 9,
      y: 2,
      spriteKey: 'rival',
      facing: 'down',
      dialogue: [],
      trainer: {
        id: 'admin_merge',
        name: 'Admin Merge',
        spriteKey: 'rival',
        party: [
          { species: 'flarat', level: 38 },
          { species: 'cactoss', level: 38 },
          { species: 'cindrake', level: 40 },
        ],
        prize: 5200,
        introText:
          'Admin Merge: So. You found the tube. Let me explain what we do here. We MERGE branches. Every Mockemon, every route, every line of the Ledger - we fold them back into the first draft. No conflicts. No duplicates. One clean history. This fragment is a merge target. Hand it over.',
        defeatText:
          'Admin Merge: Merge conflict... unresolved. The fragment rejects my changes. Fine. Take it. But know this: the first draft is still out there, and Director Nil will force-push it whether you like it or not.',
        sight: 0,
        ai: 'smart',
      },
    },
  ],
  items: [
    { id: 'lavatube_superpotion1', x: 2, y: 8, item: 'superpotion', count: 1 },
    { id: 'lavatube_embercharm1', x: 16, y: 15, item: 'embercharm', count: 1 },
  ],
  encounters: [],
  encounterRate: 0,
  signs: [],
  lockedDoors: [],
  events: [
    { x: 9, y: 20, script: 'lavatube_intro', once: 'lavatubeIntroSeen' },
    { x: 9, y: 3, script: 'lavatube_boss', once: 'lavatubeBossSeen' },
  ],
  lavaPeriod: 150,
};
