import type { GameMap } from '../types';

export const lighthouse: GameMap = {
  id: 'lighthouse',
  name: 'Tidewell Lighthouse',
  indoor: true,
  tiles: [
    'wwwwwwwwwwww',
    'wFFFFFFFFFFw',
    'wFFFFFFFFFFw',
    'wFFFFFFFFFFw',
    'wFFFFFFFFFFw',
    'wFFFFFFFFFFw',
    'wFFFFFFFFFFw',
    'wFFFFFFFFFFw',
    'wFFFFFFFFFFw',
    'wFFFFFFFFFFw',
    'wFFFFFFFFFFw',
    'wFFFFFFFFFFw',
    'wFFFFFFFFFFw',
    'wFFFFMMFFFFw',
    'wwwwwwwwwwww',
  ],
  warps: [
    { x: 5, y: 13, to: 'tidewell', tx: 6, ty: 13 },
    { x: 6, y: 13, to: 'tidewell', tx: 6, ty: 13 },
  ],
  npcs: [
    {
      id: 'npc_lighthouse_keeper',
      x: 5,
      y: 1,
      spriteKey: 'villager1',
      facing: 'down',
      script: 'lighthouse_lamp',
      dialogue: [],
    },
    {
      id: 'trainer_keeper_aide',
      x: 8,
      y: 6,
      spriteKey: 'villager2',
      facing: 'left',
      dialogue: ['Aide: I help the keeper tend the lamp. It has been dark for weeks.'],
      trainer: {
        id: 'trainer_keeper_aide',
        name: "Keeper's Aide",
        spriteKey: 'villager2',
        party: [
          { species: 'pebblit', level: 17 },
          { species: 'krabbet', level: 18 },
        ],
        prize: 700,
        introText: 'Aide: The keeper needs quiet to fix the lamp. Battle me first!',
        defeatText: 'Aide: You are serious about helping. Go talk to the keeper.',
        sight: 2,
      },
    },
  ],
  items: [],
  encounters: [],
  encounterRate: 0,
  signs: [],
  lockedDoors: [],
};
