import type { GameMap } from '../types';

export const mapletown: GameMap = {
  id: 'mapletown',
  name: 'Maple Town',
  indoor: false,
  tiles: [
    'TTTTTTTT,,TTTTTTTTTT',
    'T.......,,.........T',
    'T..RRRR....RRRR....T',
    'T..RRRR....RRRR....T',
    'T..BBDB....BDBB....T',
    'T..................T',
    'T....RRRRRR........T',
    'T....RRRRRR........T',
    'T....BBDBBB........T',
    'T........S.........T',
    'T..................T',
    'T..................T',
    'T..................T',
    'T..................T',
    'T..................T',
    'TTTTTTTTTTTTTTTTTTTT',
  ],
  warps: [
    { x: 8, y: 0, to: 'route1', tx: 8, ty: 21 },
    { x: 9, y: 0, to: 'route1', tx: 9, ty: 21 },
    { x: 7, y: 8, to: 'lab', tx: 6, ty: 7 },
  ],
  npcs: [
    {
      id: 'town_kid',
      x: 14,
      y: 10,
      spriteKey: 'villager1',
      facing: 'down',
      dialogue: [
        'Technology is amazing! They say the MockDex can hold data on 26 whole Mockemon!',
      ],
    },
    {
      id: 'daycare_lady',
      x: 16,
      y: 7,
      spriteKey: 'villager1',
      facing: 'left',
      action: 'daycare',
      dialogue: [],
    },
    {
      id: 'trade_hiker',
      x: 3,
      y: 12,
      spriteKey: 'hiker',
      facing: 'right',
      action: 'trade',
      dialogue: [],
    },
    {
      id: 'ball_giver',
      x: 10,
      y: 2,
      spriteKey: 'villager2',
      facing: 'down',
      script: 'ball_giver',
      dialogue: [],
      hiddenUntilFlag: 'starterChosen',
    },
  ],
  items: [],
  encounters: [],
  encounterRate: 0,
  signs: [{ x: 9, y: 9, text: 'MAPLE TOWN - Where journeys sprout.' }],
  lockedDoors: [
    { x: 5, y: 4, text: "It's your house. Mom says: be back for dinner... someday!" },
    { x: 12, y: 4, text: 'The door is locked. Someone is snoring inside.' },
  ],
};
