import type { GameMap } from '../types';

export const powerplant_b2: GameMap = {
  id: 'powerplant_b2',
  name: 'Voltmere Power Plant B2',
  indoor: true,
  tiles: [
    'wwwwwwwwwDwwwwwwwwww',
    'w__________________w',
    'w__________________w',
    'w__________________w',
    'w______w______w____w',
    'w__________________w',
    'w__________________w',
    'w__________________w',
    'w______w______w____w',
    'w__________________w',
    'w__________________w',
    'w__________________w',
    'w______w______w____w',
    'w__________________w',
    'w__________________w',
    'w__________________w',
    'w__________________w',
    'w__________________w',
    'w__________________w',
    'w__________________w',
    'w__________________w',
    'w__________________w',
    'w__________________w',
    'wwwwwwwwwDwwwwwwwwww',
  ],
  warps: [
    { x: 9, y: 23, to: 'powerplant_b1', tx: 9, ty: 1 },
    { x: 9, y: 0, to: 'voltmere', tx: 17, ty: 5 },
  ],
  npcs: [
    {
      id: 'grunt_pp4',
      x: 5,
      y: 18,
      spriteKey: 'villager2',
      facing: 'right',
      dialogue: ['Grunt: v2.1: Hotfix applied. You will not reach the Admin.'],
      trainer: {
        id: 'grunt_pp4',
        name: 'Rollback Grunt',
        spriteKey: 'villager2',
        party: [
          { species: 'voltkat', level: 29 },
          { species: 'zapwing', level: 29 },
        ],
        prize: 1160,
        introText: 'Grunt: Unauthorized commit detected! Reverting!',
        defeatText: 'Grunt: Revert incomplete. Pulling back.',
        sight: 3,
      },
    },
    {
      id: 'grunt_pp5',
      x: 14,
      y: 5,
      spriteKey: 'villager2',
      facing: 'left',
      dialogue: ['Grunt: v2.2: Secured core. Admin Patch holds the keys.'],
      trainer: {
        id: 'grunt_pp5',
        name: 'Rollback Grunt',
        spriteKey: 'villager2',
        party: [
          { species: 'dynabolt', level: 30 },
          { species: 'ampule', level: 29 },
        ],
        prize: 1200,
        introText: 'Grunt: You cannot force-push past me!',
        defeatText: 'Grunt: Push rejected. Retreating to Admin.',
        sight: 3,
      },
    },
    {
      id: 'admin_patch',
      x: 9,
      y: 2,
      spriteKey: 'gymleader',
      facing: 'down',
      dialogue: [],
      trainer: {
        id: 'admin_patch',
        name: 'Admin Patch',
        spriteKey: 'gymleader',
        party: [
          { species: 'voltkat', level: 30 },
          { species: 'zapwing', level: 30 },
          { species: 'dynabolt', level: 32 },
          { species: 'ampule', level: 30 },
        ],
        prize: 5000,
        introText: 'Admin Patch: CHANGELOG v3.0: Reverted challenger progress. Expected outcome: failure.',
        defeatText: 'Admin Patch: Hotfix reverted. The Power Plant is yours. Take this.',
        sight: 0,
        ai: 'leader',
        potions: 3,
      },
    },
  ],
  items: [
    { id: 'pp2_safetysash', x: 2, y: 3, item: 'safetysash', count: 1 },
    { id: 'pp2_superpotion', x: 16, y: 15, item: 'superpotion', count: 2 },
  ],
  encounters: [],
  encounterRate: 0,
  signs: [],
  lockedDoors: [],
  events: [
    { x: 9, y: 1, script: 'powerplant_boss', once: 'powerplantBossSeen' },
  ],
};
