import type { GameMap } from '../types';

export const powerplant_b1: GameMap = {
  id: 'powerplant_b1',
  name: 'Voltmere Power Plant B1',
  indoor: true,
  tiles: [
    'wwwwwwwwwDwwwwwwwwww',
    'w__________________w',
    'w__________________w',
    'w__________________w',
    'w______w______w____w',
    'w__________________w',
    'w__________________w',
    'w__________________w',
    'w______w______w____w',
    'w__________________w',
    'w__________________w',
    'w__________________w',
    'w______w______w____w',
    'w__________________w',
    'w__________________w',
    'w__________________w',
    'w__________________w',
    'w__________________w',
    'w__________________w',
    'w__________________w',
    'w__________________w',
    'w__________________w',
    'w__________________w',
    'wwwwwwwwwDwwwwwwwwww',
  ],
  warps: [
    { x: 9, y: 23, to: 'voltmere', tx: 17, ty: 5 },
    { x: 9, y: 0, to: 'powerplant_b2', tx: 9, ty: 20 },
  ],
  npcs: [
    {
      id: 'grunt_pp1',
      x: 5,
      y: 17,
      spriteKey: 'villager2',
      facing: 'right',
      dialogue: ['Grunt: v1.2: Added obstacle. Expect resistance.'],
      trainer: {
        id: 'grunt_pp1',
        name: 'Rollback Grunt',
        spriteKey: 'villager2',
        party: [
          { species: 'sparkit', level: 27 },
          { species: 'ampule', level: 27 },
        ],
        prize: 1080,
        introText: 'Grunt: Unauthorised access! Initiating conflict resolution!',
        defeatText: 'Grunt: Resolution failed. Pulling back to base branch.',
        sight: 3,
      },
    },
    {
      id: 'grunt_pp2',
      x: 14,
      y: 13,
      spriteKey: 'villager2',
      facing: 'left',
      dialogue: ['Grunt: v1.3: Patched漏洞. Your progress will be reverted.'],
      trainer: {
        id: 'grunt_pp2',
        name: 'Rollback Grunt',
        spriteKey: 'villager2',
        party: [
          { species: 'zapwing', level: 28 },
          { species: 'voltkat', level: 28 },
        ],
        prize: 1120,
        introText: 'Grunt: You are not in our changelog! Get lost!',
        defeatText: 'Grunt: Merge failed... retreating to base branch.',
        sight: 3,
      },
    },
    {
      id: 'grunt_pp3',
      x: 5,
      y: 7,
      spriteKey: 'villager2',
      facing: 'right',
      dialogue: ['Grunt: v2.0: Major rewrite. The old you is deprecated.'],
      trainer: {
        id: 'grunt_pp3',
        name: 'Rollback Grunt',
        spriteKey: 'villager2',
        party: [
          { species: 'ampule', level: 29 },
          { species: 'dynabolt', level: 28 },
        ],
        prize: 1160,
        introText: 'Grunt: Another unmerged contributor? I will rebase you!',
        defeatText: 'Grunt: Rebased... onto nothing. Ouch.',
        sight: 3,
      },
    },
  ],
  items: [
    { id: 'pp1_superpotion', x: 2, y: 2, item: 'superpotion', count: 2 },
    { id: 'pp1_thunderstone', x: 16, y: 20, item: 'thunderstone', count: 1 },
  ],
  encounters: [],
  encounterRate: 0,
  signs: [],
  lockedDoors: [],
  events: [
    { x: 9, y: 22, script: 'powerplant_intro', once: 'powerplantIntroSeen' },
  ],
};
