import type { GameMap } from '../types';

export const route3: GameMap = {
  id: 'route3',
  name: 'Route 3',
  indoor: false,
  tiles: [
    'TTTTTTTT,,TTTTTTTTTT',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG~~~T',
    'T..GGG..,,..GGGG~~~T',
    'T.......,,..GGGG...T',
    'T..GGGG.,,.........T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T.......,,..GGGG...T',
    'T..GGG..,,S........T',
    'T..GGG..,,..GGGG...T',
    'T..GGG..,,..GGGG...T',
    'T.......,,.........T',
    'T.GGGG..,,..GGGG...T',
    'T.GGGG..,,..GGGG...T',
    'T.GGGG..,,.........T',
    'T.......,,..GGGG...T',
    'T..GGGG.,,..GGGG~~~T',
    'T..GGGG.,,..GGGG~~~T',
    'T..GGGG.,,.........T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T.......,,.........T',
    'TTTTTTTT,,TTTTTTTTTT',
  ],
  warps: [
    { x: 8, y: 0, to: 'seasidecave', tx: 8, ty: 22 },
    { x: 9, y: 0, to: 'seasidecave', tx: 9, ty: 22 },
    { x: 8, y: 23, to: 'thornbury', tx: 9, ty: 18 },
    { x: 9, y: 23, to: 'thornbury', tx: 10, ty: 18 },
  ],
  npcs: [
    {
      id: 'trainer_fisher_hal',
      x: 5,
      y: 5,
      spriteKey: 'hiker',
      facing: 'right',
      dialogue: ['Hal: The sea breeze brings the best Water types to this coast!'],
      trainer: {
        id: 'trainer_fisher_hal',
        name: 'Fisher Hal',
        spriteKey: 'hiker',
        party: [
          { species: 'krabbet', level: 14 },
          { species: 'floazy', level: 15 },
        ],
        prize: 560,
        introText: 'Hal: Perfect tide for a battle! Cast your line!',
        defeatText: 'Hal: You reeled me in good. Tight lines, challenger!',
        sight: 3,
      },
    },
    {
      id: 'trainer_lass_corin',
      x: 13,
      y: 13,
      spriteKey: 'lass',
      facing: 'left',
      dialogue: ['Corin: I come to the coast to train my Water types.'],
      trainer: {
        id: 'trainer_lass_corin',
        name: 'Lass Corin',
        spriteKey: 'lass',
        party: [
          { species: 'coralily', level: 15 },
          { species: 'nibblex', level: 16 },
        ],
        prize: 640,
        introText: 'Corin: The ocean inspires me! Let us battle!',
        defeatText: 'Corin: My team washed out... time to dry off.',
        sight: 3,
      },
    },
    {
      id: 'trainer_hiker_gabe',
      x: 5,
      y: 17,
      spriteKey: 'hiker',
      facing: 'right',
      dialogue: ['Gabe: Coastal caves hide rare fossils, or so they say.'],
      trainer: {
        id: 'trainer_hiker_gabe',
        name: 'Hiker Gabe',
        spriteKey: 'hiker',
        party: [
          { species: 'pebblit', level: 16 },
          { species: 'mudlet', level: 17 },
        ],
        prize: 680,
        introText: 'Gabe: HO HO! The coast is rough! Show me your mettle!',
        defeatText: 'Gabe: Weathered away like sea cliffs! Great battle!',
        sight: 3,
      },
    },
  ],
  items: [
    { id: 'r3_potion1', x: 2, y: 2, item: 'potion', count: 1 },
    { id: 'r3_mockball1', x: 16, y: 8, item: 'mockball', count: 3 },
    { id: 'r3_oran1', x: 2, y: 20, item: 'oranberry', count: 1 },
    { id: 'r3_waterstone1', x: 18, y: 2, item: 'waterstone', count: 1 },
  ],
  encounters: [
    { species: 'floazy', minLv: 13, maxLv: 17, weight: 20 },
    { species: 'driftail', minLv: 13, maxLv: 17, weight: 18 },
    { species: 'krabbet', minLv: 13, maxLv: 17, weight: 15 },
    { species: 'nibblex', minLv: 13, maxLv: 17, weight: 12, nightWeight: 20 },
    { species: 'coralily', minLv: 13, maxLv: 17, weight: 8, nightWeight: 15 },
  ],
  encounterRate: 0.14,
  signs: [
    { x: 10, y: 9, text: 'ROUTE 3 - Coastal road to Seaside Cave and Tidewell Town.' },
  ],
  lockedDoors: [],
};
