import type { GameMap } from '../types';

export const route4: GameMap = {
  id: 'route4',
  name: 'Route 4',
  indoor: false,
  tiles: [
    'TTTTTTTT,,TTTTTTTTTT',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T.......,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T.......,,.........T',
    'T..GGGG.,,S.GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T.......,,.........T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,.........T',
    'T.......,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T.......,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'TTTTTTTT,,TTTTTTTTTT',
  ],
  warps: [
    { x: 8, y: 0, to: 'voltmere', tx: 9, ty: 18 },
    { x: 9, y: 0, to: 'voltmere', tx: 10, ty: 18 },
    { x: 8, y: 23, to: 'tidewell', tx: 9, ty: 18 },
    { x: 9, y: 23, to: 'tidewell', tx: 10, ty: 18 },
  ],
  npcs: [
    {
      id: 'trainer_rocker_zap',
      x: 5,
      y: 5,
      spriteKey: 'hiker',
      facing: 'right',
      dialogue: ['Rocker Zap: The static in the air here charges my team up!'],
      trainer: {
        id: 'trainer_rocker_zap',
        name: 'Rocker Zap',
        spriteKey: 'hiker',
        party: [
          { species: 'sparkit', level: 25 },
          { species: 'ampule', level: 25 },
        ],
        prize: 1000,
        introText: 'Rocker Zap: Feel the voltage! Let us spark this up!',
        defeatText: 'Rocker Zap: Grounded out... you conduct a great battle!',
        sight: 3,
      },
    },
    {
      id: 'trainer_lass_vel',
      x: 13,
      y: 13,
      spriteKey: 'lass',
      facing: 'left',
      dialogue: ['Vel: I come here to charge up my Electric types.'],
      trainer: {
        id: 'trainer_lass_vel',
        name: 'Lass Vel',
        spriteKey: 'lass',
        party: [
          { species: 'zapwing', level: 26 },
          { species: 'psywisp', level: 26 },
        ],
        prize: 1040,
        introText: 'Vel: My team is buzzing with energy! Battle!',
        defeatText: 'Vel: Shorted out... time to recharge.',
        sight: 3,
      },
    },
    {
      id: 'trainer_hiker_dex',
      x: 5,
      y: 17,
      spriteKey: 'hiker',
      facing: 'right',
      dialogue: ['Dex: The road to Voltmere is rocky but rewarding!'],
      trainer: {
        id: 'trainer_hiker_dex',
        name: 'Hiker Dex',
        spriteKey: 'hiker',
        party: [
          { species: 'pebblit', level: 26 },
          { species: 'mudlet', level: 27 },
        ],
        prize: 1080,
        introText: 'Dex: HO HO! The highlands spark with energy! Show me your mettle!',
        defeatText: 'Dex: Eroded away like a bad fuse! Great battle!',
        sight: 3,
      },
    },
  ],
  items: [
    { id: 'r4_superpotion', x: 2, y: 2, item: 'superpotion', count: 1 },
    { id: 'r4_thunderstone', x: 16, y: 8, item: 'thunderstone', count: 1 },
    { id: 'r4_mockball', x: 2, y: 20, item: 'mockball', count: 3 },
  ],
  encounters: [
    { species: 'ampule', minLv: 22, maxLv: 27, weight: 20 },
    { species: 'sparkit', minLv: 22, maxLv: 26, weight: 18 },
    { species: 'zapwing', minLv: 23, maxLv: 27, weight: 12, nightWeight: 20 },
    { species: 'pebblit', minLv: 22, maxLv: 27, weight: 15 },
    { species: 'mudlet', minLv: 22, maxLv: 26, weight: 10, nightWeight: 15 },
  ],
  encounterRate: 0.14,
  signs: [
    { x: 10, y: 9, text: 'ROUTE 4 - Sparks fly on the road to Voltmere City.' },
  ],
  lockedDoors: [],
};
