import { route1Encounters } from '../encounters';
import type { GameMap } from '../types';

export const route1: GameMap = {
  id: 'route1',
  name: 'Route 1',
  indoor: false,
  tiles: [
    'TTTTTTTT,,TTTTTTTTTT',
    'T.......,,.........T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T.......,,.........T',
    'T.......,,......WWWT',
    'T..GGG..,,......WWWT',
    'T..GGG..,,.........T',
    'T..GGG..,,..GGGG...T',
    'T.......,,..GGGG...T',
    'T.......,,..GGGG...T',
    'T....o..,,.........T',
    'T.......,,....GGG..T',
    'T..GGGG.,,....GGG..T',
    'T..GGGG.,,....GGG..T',
    'T..GGGG.,,.........T',
    'T.......,,.........T',
    'T.......,,...o.....T',
    'T..GG...,,.........T',
    'T..GG...,,..GGG....T',
    'T.......,,..GGG....T',
    'T.......,,.........T',
    'TTTTTTTT,,TTTTTTTTTT',
  ],
  warps: [
    { x: 8, y: 0, to: 'verdantcity', tx: 9, ty: 16 },
    { x: 9, y: 0, to: 'verdantcity', tx: 10, ty: 16 },
    { x: 8, y: 22, to: 'mapletown', tx: 8, ty: 1 },
    { x: 9, y: 22, to: 'mapletown', tx: 9, ty: 1 },
  ],
  npcs: [
    {
      id: 'trainer_ben',
      x: 12,
      y: 10,
      spriteKey: 'bugcatcher',
      facing: 'left',
      dialogue: ['Ben: My bugs buzz in perfect pitch!'],
      trainer: {
        id: 'trainer_ben',
        name: 'Bug Catcher Ben',
        spriteKey: 'bugcatcher',
        party: [
          { species: 'buzzler', level: 3 },
          { species: 'thistling', level: 3 },
        ],
        prize: 120,
        introText: 'Ben: Hey! You walked into my bug net! Battle time!',
        defeatText: 'Ben: My bugs got squashed...',
        sight: 4,
      },
    },
    {
      id: 'trainer_mia',
      x: 7,
      y: 15,
      spriteKey: 'lass',
      facing: 'right',
      dialogue: ['Mia: Fluffowl is the fluffiest. No contest.'],
      trainer: {
        id: 'trainer_mia',
        name: 'Lass Mia',
        spriteKey: 'lass',
        party: [
          { species: 'fluffowl', level: 4 },
          { species: 'nibbit', level: 4 },
        ],
        prize: 150,
        introText: "Mia: You look new! Let's see what you've got!",
        defeatText: 'Mia: Aww, my fluffy team!',
        sight: 3,
      },
    },
    {
      id: 'trainer_cliff',
      x: 12,
      y: 18,
      spriteKey: 'hiker',
      facing: 'left',
      dialogue: ['Cliff: The gym leader in Verdant City? Hard as a rock, that one.'],
      trainer: {
        id: 'trainer_cliff',
        name: 'Hiker Cliff',
        spriteKey: 'hiker',
        party: [
          { species: 'pebblit', level: 5 },
          { species: 'mudlet', level: 5 },
        ],
        prize: 240,
        introText: 'Cliff: HO HO! A challenger on my trail!',
        defeatText: 'Cliff: Solid battle, kid!',
        sight: 4,
      },
    },
  ],
  items: [
    { id: 'r1_potion1', x: 14, y: 7, item: 'potion', count: 1 },
    { id: 'r1_potion2', x: 16, y: 12, item: 'potion', count: 1 },
    { id: 'r1_ball1', x: 5, y: 19, item: 'mockball', count: 3 },
    { id: 'r1_moonstone', x: 17, y: 18, item: 'moonstone', count: 1 },
    { id: 'r1_thunderstone', x: 2, y: 6, item: 'thunderstone', count: 1 },
    { id: 'r1_waterstone', x: 17, y: 2, item: 'waterstone', count: 1 },
    { id: 'r1_oran', x: 2, y: 13, item: 'oranberry', count: 2 },
  ],
  encounters: route1Encounters,
  encounterRate: 0.14,
  signs: [],
  lockedDoors: [],
  events: [{ x: 5, y: 20, script: 'route1_nibbit_found', once: 'nibbitFound' }],
};
