import type { GameMap } from '../types';

export const route8: GameMap = {
  id: 'route8', name: 'Route 8', indoor: false,
  tiles: [
    'TTTTTTTT,,TTTTTTTTTT',
    'T.......,,.........T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T.......,,.........T',
    'T..GGG..,,..GGG....T',
    'T..GGG..,,.........T',
    'T.......,,..GGGG...T',
    'T.......,,..GGGG...T',
    'T..GGGG.,,.........T',
    'T..GGGG.,,..GGG....T',
    'T.......,,..GGG....T',
    'T.......,,.........T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T.......,,.........T',
    'T..GGG..,,..GGG....T',
    'T..GGG..,,.........T',
    'T.......,,..GGGG...T',
    'T.......,,..GGGG...T',
    'T..GGGG.,,.........T',
    'T..GGGG.,,..GGG....T',
    'T.......,,.........T',
    'TTTTTTTT,,TTTTTTTTTT',
  ],
  warps: [
    { x: 8, y: 0, to: 'somnium', tx: 9, ty: 18 },
    { x: 9, y: 0, to: 'somnium', tx: 10, ty: 18 },
    { x: 8, y: 23, to: 'zephyrheights', tx: 9, ty: 18 },
    { x: 9, y: 23, to: 'zephyrheights', tx: 10, ty: 18 },
  ],
  npcs: [
    { id: 'trainer_selene', x: 12, y: 4, spriteKey: 'lass', facing: 'left', dialogue: ['Selene: The moonlight reveals all.'], trainer: { id: 'trainer_selene', name: 'Stargazer Selene', spriteKey: 'lass', party: [{ species: 'somnara', level: 45 }, { species: 'psywisp', level: 45 }], prize: 1080, introText: 'Selene: The stars told me you would come. Battle!', defeatText: 'Selene: The stars were right about you...', sight: 3 } },
    { id: 'trainer_cosmo', x: 5, y: 9, spriteKey: 'hiker', facing: 'right', dialogue: ['Cosmo: Cosmic energy permeates this road.'], trainer: { id: 'trainer_cosmo', name: 'Stargazer Cosmo', spriteKey: 'hiker', party: [{ species: 'howlette', level: 46 }, { species: 'mimew', level: 46 }], prize: 1104, introText: 'Cosmo: The cosmos test you now!', defeatText: 'Cosmo: Cosmic... simply cosmic.', sight: 3 } },
    { id: 'trainer_asteria', x: 12, y: 14, spriteKey: 'lass', facing: 'left', dialogue: ['Asteria: I map the stars by night.'], trainer: { id: 'trainer_asteria', name: 'Stargazer Asteria', spriteKey: 'lass', party: [{ species: 'enigmew', level: 46 }, { species: 'somnara', level: 46 }], prize: 1104, introText: 'Asteria: Your constellation clashes with mine!', defeatText: 'Asteria: A shooting star... that was you.', sight: 4 } },
    { id: 'trainer_nyx', x: 5, y: 19, spriteKey: 'villager1', facing: 'right', dialogue: ['Nyx: The night is my domain.'], trainer: { id: 'trainer_nyx', name: 'Wanderer Nyx', spriteKey: 'villager1', party: [{ species: 'psywisp', level: 47 }, { species: 'enigmew', level: 47 }, { species: 'mimew', level: 45 }], prize: 1128, introText: 'Nyx: Dark skies, darker intentions. Battle!', defeatText: 'Nyx: The night fades before your light.', sight: 3 } },
  ],
  items: [
    { id: 'route8_superpotion', x: 16, y: 6, item: 'superpotion', count: 1 },
    { id: 'route8_moonstone', x: 2, y: 16, item: 'moonstone', count: 1 },
    { id: 'route8_sitrusberry', x: 15, y: 20, item: 'sitrusberry', count: 2 },
  ],
  encounters: [
    { species: 'somnara', minLv: 43, maxLv: 47, weight: 20, nightWeight: 30 },
    { species: 'enigmew', minLv: 43, maxLv: 46, weight: 15, nightWeight: 25 },
    { species: 'psywisp', minLv: 43, maxLv: 47, weight: 25, nightWeight: 35 },
    { species: 'howlette', minLv: 44, maxLv: 47, weight: 20 },
    { species: 'mimew', minLv: 43, maxLv: 45, weight: 10 },
  ],
  encounterRate: 0.14,
  signs: [{ x: 10, y: 9, text: 'ROUTE 8 - A moonlit road to Somnium Town.' }],
  lockedDoors: [],
};
