import type { GameMap } from '../types';

export const route6: GameMap = {
  id: 'route6',
  name: 'Route 6',
  indoor: false,
  tiles: [
    'TTTTTTTT,,TTTTTTTTTT',
    'T.......,,.S.......T',
    'T..GGG..,,..GGGG...T',
    'T..GGG..,,..GGGG...T',
    'T..GGG..,,.........T',
    'T.......,,....TTT..T',
    'T..TT...,,....TTT..T',
    'T..TT...,,.........T',
    'T.......,,..GGG....T',
    'T..GGGG.,,..GGG....T',
    'T..GGGG.,,.........T',
    'T.......,,...o.....T',
    'T....TT.,,.........T',
    'T....TT.,,..GGGG...T',
    'T.......,,..GGGG...T',
    'T..GG...,,.........T',
    'T..GG...,,....TT...T',
    'T.......,,....TT...T',
    'T.......,,.........T',
    'T..GGG..,,..GGG....T',
    'T..GGG..,,..GGG....T',
    'T.......,,.........T',
    'T.......,,.........T',
    'TTTTTTTT,,TTTTTTTTTT',
  ],
  warps: [
    { x: 8, y: 0, to: 'cinderwake', tx: 9, ty: 18 },
    { x: 9, y: 0, to: 'cinderwake', tx: 10, ty: 18 },
    { x: 8, y: 23, to: 'bloomrest', tx: 9, ty: 18 },
    { x: 9, y: 23, to: 'bloomrest', tx: 10, ty: 18 },
  ],
  npcs: [
    {
      id: 'trainer_soot',
      x: 12,
      y: 4,
      spriteKey: 'hiker',
      facing: 'left',
      dialogue: ['Soot: Ash makes lousy soil and excellent trainers.'],
      trainer: {
        id: 'trainer_soot',
        name: 'Hiker Soot',
        spriteKey: 'hiker',
        party: [
          { species: 'mudlet', level: 35 },
          { species: 'flarat', level: 36 },
        ],
        prize: 1400,
        introText: 'Soot: HO! Nobody crosses the flats without a scuffle!',
        defeatText: 'Soot: Blown clean off my feet...',
        sight: 4,
      },
    },
    {
      id: 'trainer_marla',
      x: 7,
      y: 9,
      spriteKey: 'lass',
      facing: 'right',
      dialogue: ['Marla: My team runs hot. Do not stand downwind.'],
      trainer: {
        id: 'trainer_marla',
        name: 'Lass Marla',
        spriteKey: 'lass',
        party: [
          { species: 'flarat', level: 36 },
          { species: 'cactoss', level: 36 },
        ],
        prize: 1440,
        introText: 'Marla: Cinderwake is close! Let me warm you up first!',
        defeatText: 'Marla: Out cold. Ironic.',
        sight: 3,
      },
    },
    {
      id: 'trainer_grit',
      x: 16,
      y: 13,
      spriteKey: 'villager2',
      facing: 'left',
      dialogue: ['Grit: I count the embers every night. Tonight there are more.'],
      trainer: {
        id: 'trainer_grit',
        name: 'Ash Walker Grit',
        spriteKey: 'villager2',
        party: [
          { species: 'nibblex', level: 36 },
          { species: 'pyrelisk', level: 37 },
        ],
        prize: 1480,
        introText: 'Grit: The flats belong to whoever wins. Currently me.',
        defeatText: 'Grit: Recount... I demand a recount.',
        sight: 4,
      },
    },
    {
      id: 'trainer_cinnia',
      x: 5,
      y: 16,
      spriteKey: 'bugcatcher',
      facing: 'left',
      dialogue: ['Cinnia: Bugs hate the ash. I brought lizards instead.'],
      trainer: {
        id: 'trainer_cinnia',
        name: 'Kindler Cinnia',
        spriteKey: 'bugcatcher',
        party: [
          { species: 'pyrelisk', level: 37 },
          { species: 'flarat', level: 38 },
        ],
        prize: 1520,
        introText: 'Cinnia: Six steps into the flats and already sweating? Battle me!',
        defeatText: 'Cinnia: Snuffed out. Fair enough.',
        sight: 4,
      },
    },
  ],
  items: [
    { id: 'route6_superpotion1', x: 17, y: 7, item: 'superpotion', count: 1 },
    { id: 'route6_embercharm1', x: 4, y: 11, item: 'embercharm', count: 1 },
    { id: 'route6_sitrusberry1', x: 13, y: 21, item: 'sitrusberry', count: 2 },
  ],
  encounters: [
    { species: 'flarat', minLv: 33, maxLv: 36, weight: 28 },
    { species: 'pyrelisk', minLv: 34, maxLv: 37, weight: 24 },
    { species: 'mudlet', minLv: 33, maxLv: 35, weight: 20 },
    { species: 'nibblex', minLv: 33, maxLv: 36, weight: 16, nightWeight: 30 },
    { species: 'cactoss', minLv: 34, maxLv: 37, weight: 12, nightWeight: 22 },
  ],
  encounterRate: 0.12,
  signs: [
    { x: 11, y: 1, text: 'ROUTE 6 - The ash flats. North: Cinderwake. Mind your step, it is still warm.' },
  ],
  lockedDoors: [],
};
