import type { GameMap } from '../types';

export const route5: GameMap = {
  id: 'route5',
  name: 'Route 5',
  indoor: false,
  tiles: [
    'TTTTTTTT,,TTTTTTTTTT',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T.......,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T.......,,.........T',
    'T..GGGG.,,S.GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T.......,,.........T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,.........T',
    'T.......,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T.......,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'TTTTTTTT,,TTTTTTTTTT',
  ],
  warps: [
    { x: 8, y: 0, to: 'bloomrest', tx: 9, ty: 18 },
    { x: 9, y: 0, to: 'bloomrest', tx: 10, ty: 18 },
    { x: 8, y: 23, to: 'voltmere', tx: 9, ty: 18 },
    { x: 9, y: 23, to: 'voltmere', tx: 10, ty: 18 },
  ],
  npcs: [
    {
      id: 'trainer_gardener_pip',
      x: 5,
      y: 5,
      spriteKey: 'villager1',
      facing: 'right',
      dialogue: ['Pip: The soil on this road grows the strongest Grass types!'],
      trainer: {
        id: 'trainer_gardener_pip',
        name: 'Gardener Pip',
        spriteKey: 'villager1',
        party: [
          { species: 'bloomule', level: 31 },
          { species: 'cactoss', level: 31 },
        ],
        prize: 1240,
        introText: 'Pip: My garden of battle is in full bloom! Let us go!',
        defeatText: 'Pip: Pruned beautifully. You have a green thumb for battle!',
        sight: 3,
      },
    },
    {
      id: 'trainer_lass_fern',
      x: 13,
      y: 13,
      spriteKey: 'lass',
      facing: 'left',
      dialogue: ['Fern: The air is so fresh here. Perfect for training!'],
      trainer: {
        id: 'trainer_lass_fern',
        name: 'Lass Fern',
        spriteKey: 'lass',
        party: [
          { species: 'thistling', level: 32 },
          { species: 'bloomule', level: 32 },
        ],
        prize: 1280,
        introText: 'Fern: The breeze carries pollen and battle! Come on!',
        defeatText: 'Fern: Blown away like a dandelion... lovely battle!',
        sight: 3,
      },
    },
    {
      id: 'trainer_hiker_ash',
      x: 5,
      y: 17,
      spriteKey: 'hiker',
      facing: 'right',
      dialogue: ['Ash: The road to Bloomrest is lined with rare plants!'],
      trainer: {
        id: 'trainer_hiker_ash',
        name: 'Hiker Ash',
        spriteKey: 'hiker',
        party: [
          { species: 'cactoss', level: 33 },
          { species: 'pebblit', level: 32 },
        ],
        prize: 1320,
        introText: 'Ash: HO HO! The highland flora is tough! Show me your mettle!',
        defeatText: 'Ash: Uprooted like a weed! Great battle, challenger!',
        sight: 3,
      },
    },
    {
      id: 'rival_kai_3',
      x: 10,
      y: 15,
      spriteKey: 'rival',
      facing: 'down',
      dialogue: [],
      script: 'kai_rematch_route5',
      trainer: {
        id: 'rival_kai_3',
        name: 'Rival Kai',
        spriteKey: 'rival',
        party: [
          { species: 'emberuin', level: 33 },
          { species: 'howlette', level: 33 },
          { species: 'zapwing', level: 33 },
        ],
        prize: 2000,
        introText: 'Kai: Been a while. I have been training hard since last time. Let us see who grew stronger!',
        defeatText: 'Kai: ...You are always one step ahead. Fine. Go on to Bloomrest. I will catch up.',
        sight: 0,
        ai: 'smart',
      },
    },
  ],
  items: [
    { id: 'r5_superpotion', x: 2, y: 2, item: 'superpotion', count: 2 },
    { id: 'r5_leafcharm', x: 16, y: 8, item: 'leafcharm', count: 1 },
    { id: 'r5_sitrusberry', x: 2, y: 20, item: 'sitrusberry', count: 2 },
  ],
  encounters: [
    { species: 'bloomule', minLv: 28, maxLv: 33, weight: 20 },
    { species: 'cactoss', minLv: 28, maxLv: 33, weight: 18 },
    { species: 'thistling', minLv: 28, maxLv: 32, weight: 15, nightWeight: 22 },
    { species: 'buzzler', minLv: 28, maxLv: 33, weight: 12 },
    { species: 'cocoonet', minLv: 29, maxLv: 33, weight: 8, nightWeight: 15 },
  ],
  encounterRate: 0.14,
  signs: [
    { x: 10, y: 9, text: 'ROUTE 5 - The air grows sweeter heading toward Bloomrest.' },
  ],
  lockedDoors: [],
  events: [{ x: 7, y: 20, script: 'route5_berry_collect', once: 'berriesCollected' }],
};
