import type { GameMap } from '../types';

export const route7: GameMap = {
  id: 'route7',
  name: 'Route 7',
  indoor: false,
  tiles: [
    'TTTTTTTT,,TTTTTTTTTT',
    'T........S.........T',
    'T..GGG.....GGG.....T',
    'T..GGG.....GGG.....T',
    'T..................T',
    'T....TT...TT.......T',
    'T....TT...TT.......T',
    'T..................T',
    'T..GGG....GGGG.....T',
    'T..GGG....GGGG.....T',
    'T.##############...T',
    'T.##############...T',
    'T.##############...T',
    'T..................T',
    'T..TT.........TT...T',
    'T..TT.........TT...T',
    'T..................T',
    'T..GGG....GGG......T',
    'T..GGG....GGG......T',
    'T..................T',
    'T....TT...TT.......T',
    'T....TT...TT.......T',
    'T..................T',
    'TTTTTTTT,,TTTTTTTTTT',
  ],
  warps: [
    { x: 8, y: 0, to: 'zephyrheights', tx: 9, ty: 18 },
    { x: 9, y: 0, to: 'zephyrheights', tx: 10, ty: 18 },
    { x: 8, y: 23, to: 'cinderwake', tx: 9, ty: 18 },
    { x: 9, y: 23, to: 'cinderwake', tx: 10, ty: 18 },
  ],
  npcs: [
    {
      id: 'trainer_gale1',
      x: 16,
      y: 4,
      spriteKey: 'lass',
      facing: 'left',
      dialogue: ['Gale1: The wind up here will blow you right back down!'],
      trainer: {
        id: 'trainer_gale1',
        name: 'Lass Gale',
        spriteKey: 'lass',
        party: [
          { species: 'gustling', level: 40 },
          { species: 'zapwing', level: 40 },
        ],
        prize: 1600,
        introText: 'Gale1: Careful! The switchbacks are windy and I am windier!',
        defeatText: 'Gale1: Blown away by your skill!',
        sight: 4,
      },
    },
    {
      id: 'trainer_gale2',
      x: 4,
      y: 8,
      spriteKey: 'hiker',
      facing: 'right',
      dialogue: ['Gale2: I climbed all day and the wind keeps pushing me back.'],
      trainer: {
        id: 'trainer_gale2',
        name: 'Hiker Gale',
        spriteKey: 'hiker',
        party: [
          { species: 'zapwing', level: 41 },
          { species: 'howlette', level: 41 },
        ],
        prize: 1640,
        introText: 'Gale2: HO! You made it past the wind? Prove your grit!',
        defeatText: 'Gale2: Grittier than the gravel, you are.',
        sight: 4,
      },
    },
    {
      id: 'trainer_gale3',
      x: 16,
      y: 14,
      spriteKey: 'villager2',
      facing: 'left',
      dialogue: ['Gale3: The Sky Bridge is just beyond Zephyr Heights.'],
      trainer: {
        id: 'trainer_gale3',
        name: 'Cliff Walker Gale',
        spriteKey: 'villager2',
        party: [
          { species: 'howlette', level: 42 },
          { species: 'skywyrm', level: 42 },
        ],
        prize: 1680,
        introText: 'Gale3: The mountain tests everyone. You are no exception!',
        defeatText: 'Gale3: You passed the test. The heights await.',
        sight: 4,
      },
    },
    {
      id: 'trainer_gale4',
      x: 4,
      y: 18,
      spriteKey: 'bugcatcher',
      facing: 'right',
      dialogue: ['Gale4: Even the bugs up here can fly. Adapt or fall!'],
      trainer: {
        id: 'trainer_gale4',
        name: 'Bug Catcher Gale',
        spriteKey: 'bugcatcher',
        party: [
          { species: 'skywyrm', level: 42 },
          { species: 'pyrelisk', level: 43 },
        ],
        prize: 1720,
        introText: 'Gale4: My mountain bugs do not crawl. They SOAR!',
        defeatText: 'Gale4: Soared straight into the ground. Ouch.',
        sight: 4,
      },
    },
  ],
  items: [
    { id: 'route7_superpotion1', x: 17, y: 7, item: 'superpotion', count: 1 },
    { id: 'route7_swiftfeather1', x: 2, y: 14, item: 'swiftfeather', count: 1 },
    { id: 'route7_sitrusberry1', x: 17, y: 21, item: 'sitrusberry', count: 2 },
  ],
  encounters: [
    { species: 'gustling', minLv: 38, maxLv: 41, weight: 28 },
    { species: 'zapwing', minLv: 38, maxLv: 42, weight: 24 },
    { species: 'howlette', minLv: 38, maxLv: 41, weight: 20, nightWeight: 30 },
    { species: 'skywyrm', minLv: 39, maxLv: 42, weight: 16 },
    { species: 'pyrelisk', minLv: 38, maxLv: 42, weight: 12, nightWeight: 22 },
  ],
  encounterRate: 0.12,
  signs: [
    { x: 9, y: 1, text: 'ROUTE 7 - Mountain switchbacks. Beware the wind slopes.' },
  ],
  lockedDoors: [],
  windDir: 'down',
};
