import type { GameMap } from '../types';

export const seasidecave: GameMap = {
  id: 'seasidecave',
  name: 'Seaside Cave',
  indoor: true,
  tiles: [
    'wwwwwwww__wwwwwwwwww',
    'w__________________w',
    'w__GG______________w',
    'w__S_______________w',
    'w__________________w',
    'w_____www__________w',
    'w_____w_w__________w',
    'w_____w_w__________w',
    'w_____www__________w',
    'w__________________w',
    'w__GG______________w',
    'w__GG______________w',
    'w_______GG_________w',
    'w______________GG__w',
    'w______________GG__w',
    'w__________________w',
    'w__________________w',
    'w__GG______________w',
    'w__GG______________w',
    'w__________________w',
    'w_______GG_________w',
    'w______________GG__w',
    'w__________________w',
    'wwwwwwww__wwwwwwwwww',
  ],
  warps: [
    { x: 8, y: 0, to: 'tidewell', tx: 9, ty: 18 },
    { x: 9, y: 0, to: 'tidewell', tx: 10, ty: 18 },
    { x: 8, y: 23, to: 'route3', tx: 8, ty: 1 },
    { x: 9, y: 23, to: 'route3', tx: 9, ty: 1 },
  ],
  npcs: [
    {
      id: 'trainer_cavediver_pip',
      x: 9,
      y: 12,
      spriteKey: 'hiker',
      facing: 'down',
      dialogue: ['Pip: I dive for fossils in these caves. The rare ones glow!'],
      trainer: {
        id: 'trainer_cavediver_pip',
        name: 'Cavediver Pip',
        spriteKey: 'hiker',
        party: [
          { species: 'krabbet', level: 16 },
          { species: 'pebblit', level: 17 },
        ],
        prize: 680,
        introText: 'Pip: The dark does not scare me! But your team might!',
        defeatText: 'Pip: Out-dove by a landlubber. Respect!',
        sight: 3,
      },
    },
    {
      id: 'trainer_speleaker_nod',
      x: 9,
      y: 5,
      spriteKey: 'hiker',
      facing: 'down',
      dialogue: ['Nod: Listen to the cave. It hums when fossils are near.'],
      trainer: {
        id: 'trainer_speleaker_nod',
        name: 'Speleaker Nod',
        spriteKey: 'hiker',
        party: [
          { species: 'mudlet', level: 17 },
          { species: 'silkette', level: 18 },
        ],
        prize: 720,
        introText: 'Nod: The cave spoke of you. Let us see what it meant!',
        defeatText: 'Nod: The echo fades. You are stronger than the dark.',
        sight: 2,
      },
    },
  ],
  items: [
    { id: 'sc_moonstone1', x: 2, y: 7, item: 'moonstone', count: 1 },
    { id: 'sc_potion1', x: 17, y: 15, item: 'potion', count: 1 },
    { id: 'sc_mockball1', x: 2, y: 20, item: 'mockball', count: 3 },
  ],
  encounters: [
    { species: 'pebblit', minLv: 15, maxLv: 18, weight: 20 },
    { species: 'mudlet', minLv: 15, maxLv: 18, weight: 18, nightWeight: 25 },
    { species: 'krabbet', minLv: 15, maxLv: 18, weight: 15 },
    { species: 'silkette', minLv: 15, maxLv: 18, weight: 10, nightWeight: 18 },
  ],
  encounterRate: 0.12,
  signs: [
    {
      x: 3,
      y: 3,
      text: "A faded plaque: 'Fossils of ancient Mockemon sleep here. Seek the Moon Stone.'",
    },
  ],
  lockedDoors: [],
  events: [
    { x: 8, y: 11, script: 'cave_dredge_scene', once: 'caveDredgeSeen' },
  ],
};
