import type { GameMap } from '../types';

export const skybridge: GameMap = {
  id: 'skybridge',
  name: 'Sky Bridge',
  indoor: false,
  tiles: [
    'TTTTTTTTTTTTTTTTTTTT',
    'TTTTTTT...TTTTTTTTTT',
    'TTTTTTT...TTTTTTTTTT',
    'TTTTTTT...TTTTTTTTTT',
    'TTTTTT.....TTTTTTTTT',
    'TTTTTT.....TTTTTTTTT',
    'TTTTTTT...TTTTTTTTTT',
    'TTTTTTT...TTTTTTTTTT',
    'TTTTTTT...TTTTTTTTTT',
    'TTTTTT.....TTTTTTTTT',
    'TTTTTT.....TTTTTTTTT',
    'TTTTTTT...TTTTTTTTTT',
    'TTTTTTT...TTTTTTTTTT',
    'TTTTTTT...TTTTTTTTTT',
    'TTTTTT.....TTTTTTTTT',
    'TTTTTT.....TTTTTTTTT',
    'TTTTTTT...TTTTTTTTTT',
    'TTTTTTT...TTTTTTTTTT',
    'TTTTTTT...TTTTTTTTTT',
    'TTTTTTT...TTTTTTTTTT',
    'TTTTTTT...TTTTTTTTTT',
    'TTTTTTTTTTTTTTTTTTTT',
  ],
  warps: [
    { x: 9, y: 20, to: 'zephyrheights', tx: 17, ty: 5 },
  ],
  npcs: [
    {
      id: 'grunt_sb1',
      x: 9,
      y: 4,
      spriteKey: 'villager2',
      facing: 'down',
      dialogue: ['Grunt: The bridge is ours! Nobody crosses!'],
      trainer: {
        id: 'grunt_sb1',
        name: 'Rollback Grunt',
        spriteKey: 'villager2',
        party: [
          { species: 'gustling', level: 41 },
          { species: 'zapwing', level: 41 },
        ],
        prize: 1640,
        introText: 'Grunt: Unauthorised crossing! I will push you off the bridge!',
        defeatText: 'Grunt: Pushed off... by a trainer. Embarrassing.',
        sight: 3,
      },
    },
    {
      id: 'grunt_sb2',
      x: 9,
      y: 9,
      spriteKey: 'villager2',
      facing: 'down',
      dialogue: ['Grunt: Juno is ahead. You are too slow to catch us!'],
      trainer: {
        id: 'grunt_sb2',
        name: 'Rollback Grunt',
        spriteKey: 'villager2',
        party: [
          { species: 'zapwing', level: 42 },
          { species: 'howlette', level: 42 },
        ],
        prize: 1680,
        introText: 'Grunt: Hot pursuit? We expected a slower build cycle!',
        defeatText: 'Grunt: Build failed. Falling back.',
        sight: 3,
      },
    },
    {
      id: 'grunt_sb3',
      x: 9,
      y: 14,
      spriteKey: 'villager2',
      facing: 'down',
      dialogue: ['Grunt: The hostage is just beyond me. You will never make it!'],
      trainer: {
        id: 'grunt_sb3',
        name: 'Rollback Grunt',
        spriteKey: 'villager2',
        party: [
          { species: 'howlette', level: 43 },
          { species: 'skywyrm', level: 43 },
        ],
        prize: 1720,
        introText: 'Grunt: Final guard! My patch set says you stop here!',
        defeatText: 'Grunt: Patch rejected. Go on, then. She is yours.',
        sight: 3,
      },
    },
  ],
  items: [
    { id: 'skybridge_superpotion1', x: 7, y: 5, item: 'superpotion', count: 1 },
    { id: 'skybridge_swiftfeather1', x: 10, y: 15, item: 'swiftfeather', count: 1 },
  ],
  encounters: [],
  encounterRate: 0,
  signs: [],
  lockedDoors: [],
  events: [
    { x: 9, y: 19, script: 'skybridge_chase', once: 'skybridgeChaseSeen' },
    { x: 9, y: 1, script: 'skybridge_rescue', once: 'junoRescued' },
  ],
};
