import type { GameMap } from '../types';

export const somnium: GameMap = {
  id: 'somnium', name: 'Somnium Town', indoor: false,
  tiles: [
    'TTTTTTTTT,,TTTTTTTTTTT',
    'T....................T',
    'T..RRRR...RRRR..RRRR.T',
    'T..RRRR...RRRR..RRRR.T',
    'T..BDBB...BBDB..BDBB.T',
    'T....................T',
    'T....................T',
    'T.......RRRRRR.......T',
    'T.......BBBDBB.......T',
    'T.........S..........T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T..............S.....T',
    'T....................T',
    'T....................T',
    'T....................T',
    'TTTTTTTTT,,TTTTTTTTTTT',
  ],
  warps: [
    { x: 4, y: 4, to: 'center_somnium', tx: 6, ty: 5 },
    { x: 12, y: 4, to: 'mart_somnium', tx: 6, ty: 5 },
    { x: 11, y: 8, to: 'gym8', tx: 6, ty: 11 },
    { x: 17, y: 4, to: 'observatory', tx: 6, ty: 12 },
    { x: 9, y: 0, to: 'nullpeak_1f', tx: 9, ty: 20 },
    { x: 10, y: 0, to: 'nullpeak_1f', tx: 10, ty: 20 },
    { x: 20, y: 9, to: 'victorytrail', tx: 9, ty: 20 },
    { x: 9, y: 19, to: 'route8', tx: 8, ty: 22 },
    { x: 10, y: 19, to: 'route8', tx: 9, ty: 22 },
  ],
  npcs: [
    { id: 'somnium_dreamer1', x: 6, y: 11, spriteKey: 'villager1', facing: 'down', dialogue: ['The dreams here are so vivid. I almost prefer them to waking.'] },
    { id: 'somnium_dreamer2', x: 15, y: 12, spriteKey: 'villager2', facing: 'left', dialogue: ['Somnium means dream in the old tongue. Fitting, no?'] },
    { id: 'somnium_sage', x: 8, y: 14, spriteKey: 'professor', facing: 'down', dialogue: ['The Observatory peers through stars and dreams alike. Director Nil once studied there...'] },
    { id: 'somnium_child', x: 14, y: 6, spriteKey: 'lass', facing: 'right', dialogue: ['Leader Mira says my dreams will show me the way someday!'] },
  ],
  items: [],
  encounters: [],
  encounterRate: 0,
  signs: [
    { x: 10, y: 9, text: 'SOMNIUM TOWN - Gym Leader Mira, the Dream Interpreter.' },
    { x: 15, y: 15, text: 'SOMNIUM OBSERVATORY - Peering through dreams and stars alike.' },
  ],
  lockedDoors: [],
  gates: [
    { x: 9, y: 0, flag: 'nullpeakOpen', text: 'A sealed path. The Observatory must reveal the coordinates first.' },
    { x: 10, y: 0, flag: 'nullpeakOpen', text: 'A sealed path. The Observatory must reveal the coordinates first.' },
    { x: 20, y: 9, flag: 'leagueOpen', text: 'Victory Trail. Eight badges are required.' },
  ],
};
