import type { GameMap } from '../types';

export const summitnull: GameMap = {
  id: 'summitnull', name: 'Summit Null', indoor: true,
  tiles: [
    'wwwwwwwwwwwwwwwwwwww',
    'wFFFFFFFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wwwwwwwwwFwwwwwwwwww',
    'wFFFFFFFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wwwwwwwwwFwwwwwwwwww',
    'wFFFFFFFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wwwwwwwwwFwwwwwwwwww',
    'wFFFFFFFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wwwwwwwwwFwwwwwwwwww',
    'wFFFFFFFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wFFFFFFFFFFFFFFFFFFw',
    'wwwwwwwwwMMwwwwwwwww',
  ],
  warps: [
    { x: 9, y: 21, to: 'victorytrail', tx: 9, ty: 1 },
    { x: 10, y: 21, to: 'victorytrail', tx: 9, ty: 1 },
  ],
  npcs: [
    { id: 'elite_ryn', x: 9, y: 2, spriteKey: 'gymleader', facing: 'down', dialogue: [], trainer: { id: 'elite_ryn', name: 'Elite Ryn', spriteKey: 'gymleader', party: [{ species: 'bouldron', level: 52 }, { species: 'fossilisk', level: 52 }, { species: 'cactoss', level: 53 }], prize: 6360, introText: 'Ryn: The earth shifts beneath your feet, challenger. I am Elite Ryn, and the ground obeys me.', defeatText: 'Ryn: You shattered my foundation. Proceed, if the others allow it.', sight: 0, ai: 'leader', potions: 3 } },
    { id: 'elite_calla', x: 9, y: 6, spriteKey: 'gymleader', facing: 'down', dialogue: [], trainer: { id: 'elite_calla', name: 'Elite Calla', spriteKey: 'gymleader', party: [{ species: 'torrentle', level: 53 }, { species: 'coralily', level: 53 }, { species: 'bloomule', level: 54 }], prize: 6480, introText: 'Calla: Water flows, flowers bloom. I am Elite Calla. Show me your current!', defeatText: 'Calla: Your current overwhelmed my garden. The next Elite awaits.', sight: 0, ai: 'leader', potions: 3 } },
    { id: 'elite_volt', x: 9, y: 10, spriteKey: 'gymleader', facing: 'down', dialogue: [], trainer: { id: 'elite_volt', name: 'Elite Volt', spriteKey: 'gymleader', party: [{ species: 'dynabolt', level: 54 }, { species: 'zapwing', level: 54 }, { species: 'skywyrm', level: 55 }], prize: 6600, introText: 'Volt: Lightning strikes without warning. I am Elite Volt. Brace yourself!', defeatText: 'Volt: You grounded my assault. One Elite remains.', sight: 0, ai: 'leader', potions: 3 } },
    { id: 'elite_noct', x: 9, y: 14, spriteKey: 'gymleader', facing: 'down', dialogue: [], trainer: { id: 'elite_noct', name: 'Elite Noct', spriteKey: 'gymleader', party: [{ species: 'oraculum', level: 55 }, { species: 'somnara', level: 55 }, { species: 'enigmew', level: 55 }], prize: 6720, introText: 'Noct: The mind sees all, challenger. I am Elite Noct. Your thoughts are already mine.', defeatText: 'Noct: You clouded my vision. The Champion is beyond this gate. Go.', sight: 0, ai: 'leader', potions: 3 } },
    { id: 'champion_kai', x: 9, y: 18, spriteKey: 'rival', facing: 'down', dialogue: [], trainer: { id: 'champion_kai', name: 'Champion Kai', spriteKey: 'rival', party: [{ species: 'howlette', level: 55 }, { species: 'voltkat', level: 55 }, { species: 'krabbet', level: 56 }, { species: 'cindrake', level: 56 }, { species: 'lumoth', level: 56 }], prize: 12000, introText: 'Kai: We started in Maple Town, both of us. Look how far we came. But only one of us leaves this room as Champion. Ready? Let us make this the best battle of our lives!', defeatText: 'Kai: That was incredible. You earned it, truly. Go on, take your place. You are the new Champion of the Mocca region!', sight: 0, ai: 'leader', potions: 4 } },
  ],
  items: [],
  encounters: [],
  encounterRate: 0,
  signs: [],
  lockedDoors: [],
  events: [{ x: 9, y: 19, script: 'champion_intro', once: 'championIntroSeen' }],
  gates: [
    { x: 9, y: 3, flag: 'elite1Beaten', text: 'A sealed gate. Defeat Elite Ryn to pass.' },
    { x: 9, y: 7, flag: 'elite2Beaten', text: 'A sealed gate. Defeat Elite Calla to pass.' },
    { x: 9, y: 11, flag: 'elite3Beaten', text: 'A sealed gate. Defeat Elite Volt to pass.' },
    { x: 9, y: 15, flag: 'elite4Beaten', text: 'A sealed gate. Defeat Elite Noct to pass.' },
    { x: 9, y: 17, flag: 'championOpen', text: 'The final gate. The Champion awaits.' },
  ],
};
