import type { GameMap } from '../types';

export const thornbury: GameMap = {
  id: 'thornbury',
  name: 'Thornbury',
  indoor: false,
  tiles: [
    'TTTTTTTTT,,TTTTTTTTTTT',
    'T....................T',
    'T..RRRR...RRRR.RRRR..T',
    'T..RRRR...RRRR.RRRR..T',
    'T..BDBB...BBDB.BBDB..T',
    'T....................T',
    'T....................T',
    'T.......RRRRRR.......T',
    'T.......BBBDBB.......T',
    'T.........S..........T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'TTTTTTTTT,,TTTTTTTTTTT',
  ],
  warps: [
    { x: 9, y: 0, to: 'route3', tx: 8, ty: 22 },
    { x: 10, y: 0, to: 'route3', tx: 9, ty: 22 },
    { x: 9, y: 19, to: 'verdantwoods', tx: 8, ty: 22 },
    { x: 10, y: 19, to: 'verdantwoods', tx: 9, ty: 22 },
    { x: 4, y: 4, to: 'center_thornbury', tx: 6, ty: 5 },
    { x: 12, y: 4, to: 'mart_thornbury', tx: 6, ty: 5 },
    { x: 11, y: 8, to: 'gym2', tx: 6, ty: 11 },
    { x: 17, y: 4, to: 'contest_hall', tx: 6, ty: 10 },
  ],
  npcs: [
    {
      id: 'thornbury_npc1',
      x: 6,
      y: 10,
      spriteKey: 'villager1',
      facing: 'down',
      dialogue: [
        'Did you know? Bug types keep fighting even when burned.',
        'Silk does not catch fire easily. A handy trait!',
      ],
    },
    {
      id: 'thornbury_npc2',
      x: 15,
      y: 12,
      spriteKey: 'villager2',
      facing: 'left',
      dialogue: [
        'They say a Daycare will open east of town someday.',
        'Somewhere to leave eggs and let them grow!',
      ],
    },
    {
      id: 'thornbury_npc3',
      x: 3,
      y: 12,
      spriteKey: 'villager1',
      facing: 'right',
      dialogue: [
        "Thornbury's silk weavers are the finest in Mocca.",
        'Leader Weave taught them all.',
      ],
    },
    {
      id: 'thornbury_npc4',
      x: 14,
      y: 6,
      spriteKey: 'lass',
      facing: 'down',
      dialogue: [
        'The Contest Hall runs Bug Catching Contests on weekends.',
        'Sign up inside if you fancy yourself a catcher!',
      ],
    },
  ],
  items: [],
  encounters: [],
  encounterRate: 0,
  signs: [
    { x: 10, y: 9, text: 'THORNBURY - Silk Gym: Leader Weave, the Patient Thread.' },
  ],
  lockedDoors: [],
};
