import type { GameMap } from '../types';

export const tidewell: GameMap = {
  id: 'tidewell',
  name: 'Tidewell Town',
  indoor: false,
  tiles: [
    'TTTTTTTTT,,TTTTTTTTTTT',
    'T....................T',
    'T..RRRR...RRRR.RRRR..T',
    'T..RRRR...RRRR.RRRR..T',
    'T..BDBB...BBDB.BBDB..T',
    'T....................T',
    'T....................T',
    'T.......RRRRRR.......T',
    'T.......BBBDBB.......T',
    'T.........S..........T',
    'T....................T',
    'T.....RRRR...........T',
    'T.....DBBB...........T',
    'T....................T',
    'T................WWWWT',
    'T................WWWWT',
    'T................WWWWT',
    'T...............WWWWWT',
    'T................WWWWT',
    'TTTTTTTTT,,TTTTTTTTTTT',
  ],
  warps: [
    { x: 9, y: 0, to: 'route4', tx: 8, ty: 22 },
    { x: 10, y: 0, to: 'route4', tx: 9, ty: 22 },
    { x: 9, y: 19, to: 'seasidecave', tx: 8, ty: 1 },
    { x: 10, y: 19, to: 'seasidecave', tx: 9, ty: 1 },
    { x: 4, y: 4, to: 'center_tidewell', tx: 6, ty: 5 },
    { x: 12, y: 4, to: 'mart_tidewell', tx: 6, ty: 5 },
    { x: 11, y: 8, to: 'gym3', tx: 6, ty: 11 },
    { x: 17, y: 4, to: 'museum', tx: 6, ty: 10 },
    { x: 6, y: 12, to: 'lighthouse', tx: 6, ty: 12 },
  ],
  npcs: [
    {
      id: 'tidewell_npc1',
      x: 6,
      y: 10,
      spriteKey: 'villager1',
      facing: 'down',
      dialogue: [
        'The Tide Badge lets you wade through shallow water.',
        'Look for wavy blue tiles on routes. They hide items!',
      ],
    },
    {
      id: 'tidewell_npc2',
      x: 15,
      y: 14,
      spriteKey: 'villager2',
      facing: 'right',
      dialogue: [
        'The ferry to eastern Mocca ran aground years ago.',
        "Nobody's fixed the route since. The dock rots.",
      ],
    },
    {
      id: 'tidewell_npc3',
      x: 8,
      y: 13,
      spriteKey: 'villager1',
      facing: 'down',
      dialogue: [
        "The old lighthouse lamp went dark.",
        "The keeper's been fumbling with it for weeks.",
      ],
    },
    {
      id: 'tidewell_npc4',
      x: 15,
      y: 6,
      spriteKey: 'lass',
      facing: 'left',
      dialogue: [
        'The museum revived a Mockemon from a fossil!',
        'A real ancient creature, walking around. Amazing!',
      ],
    },
  ],
  items: [],
  encounters: [],
  encounterRate: 0,
  signs: [
    { x: 10, y: 9, text: 'TIDEWELL TOWN - Tide Gym: Leader Nerin, the Unyielding Tide.' },
  ],
  lockedDoors: [],
};
