import type { GameMap } from '../types';

export const verdantcity: GameMap = {
  id: 'verdantcity',
  name: 'Verdant City',
  indoor: false,
  tiles: [
    'TTTTTTTTT,,TTTTTTTTTTT',
    'T....................T',
    'T..RRRR...RRRR.......T',
    'T..RRRR...RRRR.......T',
    'T..BDBB...BBDB.......T',
    'T....................T',
    'T.......RRRRRR.......T',
    'T.......RRRRRR.......T',
    'T.......BBBDBB.......T',
    'T.........S..........T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'TTTTTTTTT,,TTTTTTTTTTT',
  ],
  warps: [
    { x: 4, y: 4, to: 'center', tx: 6, ty: 5 },
    { x: 12, y: 4, to: 'mart', tx: 6, ty: 5 },
    { x: 11, y: 8, to: 'gym', tx: 6, ty: 11 },
    { x: 9, y: 17, to: 'route1', tx: 8, ty: 1 },
    { x: 10, y: 17, to: 'route1', tx: 9, ty: 1 },
    { x: 9, y: 0, to: 'verdantwoods', tx: 8, ty: 22 },
    { x: 10, y: 0, to: 'verdantwoods', tx: 9, ty: 22 },
  ],
  npcs: [
    {
      id: 'city_tip1',
      x: 6,
      y: 10,
      spriteKey: 'villager1',
      facing: 'down',
      dialogue: ['The Mock Center heals your whole team for free. Bless them.'],
    },
    {
      id: 'city_tip2',
      x: 15,
      y: 12,
      spriteKey: 'villager2',
      facing: 'left',
      dialogue: [
        "Leader Terra's Rock-types are super sturdy!",
        'Grass and Water moves will crack them right open.',
      ],
    },
    {
      id: 'city_woods_hint',
      x: 8,
      y: 1,
      spriteKey: 'villager1',
      facing: 'right',
      dialogue: ['The woods north of town are thick with bugs. Thornbury lies beyond.'],
    },
    {
      id: 'rival_kai_1_npc',
      x: 15,
      y: 14,
      spriteKey: 'rival',
      facing: 'down',
      script: 'kai_encounter_1',
      dialogue: [],
      hiddenAfterFlag: 'kaiEnc1Won',
    },
  ],
  items: [],
  encounters: [],
  encounterRate: 0,
  signs: [{ x: 10, y: 9, text: 'VERDANT CITY - Verdant Gym: Leader Terra, the Unshakable Stone.' }],
  lockedDoors: [],
  events: [{ x: 4, y: 5, script: 'vc_grunt_extort', once: 'vcGruntCleared' }],
};
