import type { GameMap } from '../types';

export const verdantwoods: GameMap = {
  id: 'verdantwoods',
  name: 'Verdant Woods',
  indoor: false,
  tiles: [
    'TTTTTTTT,,TTTTTTTTTT',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T..GGG..,,..GGGG...T',
    'T..GGG..,,..GGGG...T',
    'T.......,,.........T',
    'T.GGGG..,,..GGGG...T',
    'T.GGGG..,,..GGGG...T',
    'T.GGGG..,,..GGGG...T',
    'T.......,,.........T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T.......,,.........T',
    'T.GGGG..,,...GGGG..T',
    'T.GGGG..,,...GGGG..T',
    'T.GGGG..,,...GGGG..T',
    'T.......,,.........T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T..GGGG.,,..GGGG...T',
    'T.......,,.........T',
    'TTTTTTTT,,TTTTTTTTTT',
  ],
  warps: [
    { x: 8, y: 0, to: 'thornbury', tx: 9, ty: 18 },
    { x: 9, y: 0, to: 'thornbury', tx: 10, ty: 18 },
    { x: 8, y: 23, to: 'verdantcity', tx: 9, ty: 1 },
    { x: 9, y: 23, to: 'verdantcity', tx: 10, ty: 1 },
  ],
  npcs: [
    {
      id: 'trainer_bug_net_1',
      x: 5,
      y: 5,
      spriteKey: 'bugcatcher',
      facing: 'right',
      dialogue: ['Net: The woods are crawling with bugs! Perfect for my collection.'],
      trainer: {
        id: 'trainer_bug_net_1',
        name: 'Bug Catcher Net',
        spriteKey: 'bugcatcher',
        party: [
          { species: 'buzzler', level: 8 },
          { species: 'cocoonet', level: 9 },
          { species: 'thistling', level: 10 },
        ],
        prize: 360,
        introText: 'Net: A rival bug catcher! Let me see your net work!',
        defeatText: 'Net: Your bugs are tougher than mine... net loss.',
        sight: 3,
      },
    },
    {
      id: 'trainer_silk_girl',
      x: 13,
      y: 13,
      spriteKey: 'lass',
      facing: 'left',
      dialogue: ['Mara: I come here to catch silk-spinning bugs. They are so elegant!'],
      trainer: {
        id: 'trainer_silk_girl',
        name: 'Lass Mara',
        spriteKey: 'lass',
        party: [
          { species: 'silkette', level: 9 },
          { species: 'fluffowl', level: 10 },
        ],
        prize: 400,
        introText: 'Mara: Oh, are you heading to Thornbury too? Battle first!',
        defeatText: 'Mara: My elegant team was outmatched... how unladylike!',
        sight: 3,
      },
    },
    {
      id: 'trainer_web_boy',
      x: 5,
      y: 17,
      spriteKey: 'bugcatcher',
      facing: 'right',
      dialogue: ['Webb: I weave my net like silk. Thornbury will train me further!'],
      trainer: {
        id: 'trainer_web_boy',
        name: 'Bug Catcher Webb',
        spriteKey: 'bugcatcher',
        party: [
          { species: 'cocoonet', level: 10 },
          { species: 'silkette', level: 11 },
          { species: 'buzzler', level: 12 },
        ],
        prize: 480,
        introText: 'Webb: The web of fate has caught you! Bug battle!',
        defeatText: 'Webb: My web was torn apart... on to Thornbury!',
        sight: 3,
      },
    },
  ],
  items: [
    { id: 'vw_potion1', x: 2, y: 2, item: 'potion', count: 1 },
    { id: 'vw_mockball1', x: 16, y: 8, item: 'mockball', count: 3 },
    { id: 'vw_oran1', x: 2, y: 20, item: 'oranberry', count: 1 },
  ],
  encounters: [
    { species: 'buzzler', minLv: 7, maxLv: 11, weight: 25 },
    { species: 'cocoonet', minLv: 7, maxLv: 11, weight: 15 },
    { species: 'thistling', minLv: 7, maxLv: 11, weight: 20, nightWeight: 30 },
    { species: 'silkette', minLv: 7, maxLv: 11, weight: 15, nightWeight: 25 },
    { species: 'fluffowl', minLv: 7, maxLv: 11, weight: 10 },
  ],
  encounterRate: 0.15,
  signs: [],
  lockedDoors: [],
  events: [
    { x: 9, y: 9, script: 'woods_grunt_block', once: 'woodsGruntCleared' },
  ],
};
