import type { GameMap } from '../types';

export const victorytrail: GameMap = {
  id: 'victorytrail', name: 'Victory Trail', indoor: false,
  tiles: [
    'TTTTTTTT,,TTTTTTTTTT',
    'T..................T',
    'T..GGGG....GGGG....T',
    'T..GGGG....GGGG....T',
    'T..................T',
    'T....GGGG....GGGG..T',
    'T....GGGG....GGGG..T',
    'T..................T',
    'T..................T',
    'T..GGGG....GGGG....T',
    'T..GGGG....GGGG....T',
    'T..................T',
    'T..................T',
    'T....GGGG....GGGG..T',
    'T....GGGG....GGGG..T',
    'T..................T',
    'T..GGGG....GGGG....T',
    'T..GGGG....GGGG....T',
    'T..................T',
    'T..................T',
    'T..................T',
    'TTTTTTTTTDTTTTTTTTTT',
  ],
  warps: [
    { x: 8, y: 0, to: 'summitnull', tx: 9, ty: 20 },
    { x: 9, y: 0, to: 'summitnull', tx: 10, ty: 20 },
    { x: 9, y: 21, to: 'somnium', tx: 19, ty: 9 },
  ],
  npcs: [
    { id: 'trainer_ace_drake', x: 8, y: 4, spriteKey: 'hiker', facing: 'right', dialogue: ['Drake: The league awaits. Show me your strength!'], trainer: { id: 'trainer_ace_drake', name: 'Ace Trainer Drake', spriteKey: 'hiker', party: [{ species: 'bouldron', level: 50 }, { species: 'cactoss', level: 51 }], prize: 2448, introText: 'Drake: Rock and ground, unbreakable! Battle!', defeatText: 'Drake: You cracked my defense wide open.', sight: 4, ai: 'smart' } },
    { id: 'trainer_ace_sora', x: 13, y: 7, spriteKey: 'lass', facing: 'left', dialogue: ['Sora: The sky is the limit.'], trainer: { id: 'trainer_ace_sora', name: 'Ace Trainer Sora', spriteKey: 'lass', party: [{ species: 'skywyrm', level: 51 }, { species: 'zapwing', level: 50 }], prize: 2448, introText: 'Sora: Soar with me! Sky battle!', defeatText: 'Sora: You brought me back to earth...', sight: 4, ai: 'smart' } },
    { id: 'trainer_ace_ember', x: 8, y: 11, spriteKey: 'bugcatcher', facing: 'right', dialogue: ['Ember: Fire burns brightest on the trail.'], trainer: { id: 'trainer_ace_ember', name: 'Ace Trainer Ember', spriteKey: 'bugcatcher', party: [{ species: 'pyrelisk', level: 52 }, { species: 'cindrake', level: 51 }], prize: 2496, introText: 'Ember: My fire will light your way to defeat!', defeatText: 'Ember: Extinguished... you are strong.', sight: 4, ai: 'smart' } },
    { id: 'trainer_ace_sage', x: 13, y: 15, spriteKey: 'villager1', facing: 'left', dialogue: ['Sage: Wisdom and power. Both are needed.'], trainer: { id: 'trainer_ace_sage', name: 'Ace Trainer Sage', spriteKey: 'villager1', party: [{ species: 'oraculum', level: 52 }, { species: 'somnara', level: 51 }], prize: 2496, introText: 'Sage: The mind is the ultimate weapon!', defeatText: 'Sage: Outsmarted. The league is yours to challenge.', sight: 4, ai: 'smart' } },
  ],
  items: [
    { id: 'victorytrail_superpotion1', x: 5, y: 8, item: 'superpotion', count: 1 },
    { id: 'victorytrail_superpotion2', x: 14, y: 12, item: 'superpotion', count: 1 },
    { id: 'victorytrail_sitrusberry', x: 3, y: 18, item: 'sitrusberry', count: 2 },
  ],
  encounters: [
    { species: 'bouldron', minLv: 48, maxLv: 52, weight: 25 },
    { species: 'cactoss', minLv: 48, maxLv: 51, weight: 20 },
    { species: 'skywyrm', minLv: 49, maxLv: 52, weight: 15, nightWeight: 22 },
    { species: 'pyrelisk', minLv: 48, maxLv: 52, weight: 20 },
    { species: 'oraculum', minLv: 50, maxLv: 52, weight: 10, nightWeight: 20 },
  ],
  encounterRate: 0.12,
  signs: [{ x: 10, y: 9, text: 'VICTORY TRAIL - Only the worthy may pass to Summit Null.' }],
  lockedDoors: [],
};
