import type { GameMap } from '../types';

export const voltmere: GameMap = {
  id: 'voltmere',
  name: 'Voltmere City',
  indoor: false,
  tiles: [
    'TTTTTTTTT,,TTTTTTTTTTT',
    'T....................T',
    'T..RRRR...RRRR.RRRR..T',
    'T..RRRR...RRRR.RRRR..T',
    'T..BDBB...BBDB.BBDB..T',
    'T....................T',
    'T.......RRRRRR.......T',
    'T.......RRRRRR.......T',
    'T.......BBBDBB.......T',
    'T.........S..........T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T...............S....T',
    'T....................T',
    'T....................T',
    'T....................T',
    'TTTTTTTTT,,TTTTTTTTTTT',
  ],
  warps: [
    { x: 4, y: 4, to: 'center_voltmere', tx: 6, ty: 5 },
    { x: 12, y: 4, to: 'mart_voltmere', tx: 6, ty: 5 },
    { x: 11, y: 8, to: 'gym4', tx: 6, ty: 11 },
    { x: 17, y: 4, to: 'powerplant_b1', tx: 9, ty: 20 },
    { x: 9, y: 19, to: 'route4', tx: 8, ty: 22 },
    { x: 10, y: 19, to: 'route4', tx: 9, ty: 22 },
    { x: 9, y: 0, to: 'route5', tx: 8, ty: 22 },
    { x: 10, y: 0, to: 'route5', tx: 9, ty: 22 },
  ],
  npcs: [
    {
      id: 'voltmere_npc1',
      x: 6,
      y: 11,
      spriteKey: 'villager1',
      facing: 'down',
      dialogue: [
        'The Power Plant hums day and night. Sometimes the lights flicker when Team Rollback pokes around.',
      ],
    },
    {
      id: 'voltmere_npc2',
      x: 15,
      y: 12,
      spriteKey: 'villager2',
      facing: 'left',
      dialogue: [
        'Leader Dyna trained at the Power Plant. Her Mockemon hit like a thunderbolt!',
      ],
    },
    {
      id: 'voltmere_npc3',
      x: 8,
      y: 14,
      spriteKey: 'professor',
      facing: 'down',
      dialogue: [
        'Electric types thrive here. The magnetic field from the Power Plant energizes them.',
      ],
    },
    {
      id: 'voltmere_npc4',
      x: 14,
      y: 6,
      spriteKey: 'lass',
      facing: 'left',
      dialogue: [
        'I tried to challenge the Gym but those switch puzzles short-circuited my brain.',
      ],
    },
  ],
  items: [],
  encounters: [],
  encounterRate: 0,
  signs: [
    { x: 10, y: 9, text: 'VOLTMERE CITY - Gym Leader Dyna electrifies the competition.' },
    { x: 15, y: 15, text: 'VOLTMERE POWER PLANT - Closed to unauthorized personnel.' },
  ],
  lockedDoors: [],
};
