import type { GameMap } from '../types';

export const zephyrheights: GameMap = {
  id: 'zephyrheights',
  name: 'Zephyr Heights',
  indoor: false,
  tiles: [
    'TTTTTTTTT,,TTTTTTTTTTT',
    'T....................T',
    'T..RRRR...RRRR.RRRR..T',
    'T..RRRR...RRRR.RRRR..T',
    'T..BDBB...BBDB.BBDB..T',
    'T..................S.T',
    'T.......RRRRRR.......T',
    'T.......RRRRRR.......T',
    'T.......BBBDBB.......T',
    'T.........S..........T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'T....................T',
    'TTTTTTTTT,,TTTTTTTTTTT',
  ],
  warps: [
    { x: 4, y: 4, to: 'center_zephyrheights', tx: 6, ty: 5 },
    { x: 12, y: 4, to: 'mart_zephyrheights', tx: 6, ty: 5 },
    { x: 11, y: 8, to: 'gym7', tx: 6, ty: 11 },
    { x: 17, y: 4, to: 'skybridge', tx: 9, ty: 20 },
    { x: 9, y: 19, to: 'route7', tx: 8, ty: 22 },
    { x: 10, y: 19, to: 'route7', tx: 9, ty: 22 },
    { x: 9, y: 0, to: 'route8', tx: 8, ty: 22 },
    { x: 10, y: 0, to: 'route8', tx: 9, ty: 22 },
  ],
  npcs: [
    {
      id: 'sky_feather_npc',
      x: 6,
      y: 12,
      spriteKey: 'villager1',
      facing: 'down',
      script: 'sky_feather',
      dialogue: [],
    },
    {
      id: 'zephyr_tip1',
      x: 15,
      y: 10,
      spriteKey: 'villager2',
      facing: 'left',
      dialogue: [
        'The Gale Badge? It lets you use the Wing Whistle to fly to any town you have visited.',
        'Beat Leader Aeris and the whole region opens up to you.',
      ],
    },
    {
      id: 'zephyr_tip2',
      x: 3,
      y: 12,
      spriteKey: 'villager1',
      facing: 'right',
      dialogue: [
        'Everything here is built on stilts. One bad gust and... well, best not to think about it.',
      ],
    },
    {
      id: 'zephyr_tip3',
      x: 15,
      y: 15,
      spriteKey: 'lass',
      facing: 'down',
      dialogue: [
        'They say Juno was taken across the Sky Bridge. Dangerous place, that.',
        'If you are going after her, be ready for a fight.',
      ],
    },
    {
      id: 'zephyr_tip4',
      x: 5,
      y: 16,
      spriteKey: 'hiker',
      facing: 'up',
      dialogue: [
        'The wind tiles in the gym push you sideways. Enter from the right side or you will be blown back!',
      ],
    },
  ],
  items: [],
  encounters: [],
  encounterRate: 0,
  signs: [
    { x: 10, y: 9, text: 'ZEPHYR HEIGHTS - Gym: Leader Aeris, the Sky Dancer. Gale Badge.' },
    { x: 19, y: 5, text: 'SKY BRIDGE - A rope bridge above the clouds. Not for the faint of heart.' },
  ],
  lockedDoors: [],
};
