// Original pixel-art sprites for Pocket Mockster. 16x16 grids, '.' = transparent.

export interface Sprite {
  pal: Record<string, string>;
  rows: string[];
}

export function drawSprite(
  ctx: CanvasRenderingContext2D,
  spr: Sprite,
  x: number,
  y: number,
  scale: number,
  flip = false,
): void {
  for (let r = 0; r < spr.rows.length; r++) {
    const row = spr.rows[r];
    for (let c = 0; c < row.length; c++) {
      const ch = row[c];
      if (ch === '.') continue;
      const color = spr.pal[ch];
      if (!color) continue;
      const cx = flip ? row.length - 1 - c : c;
      ctx.fillStyle = color;
      ctx.fillRect(x + cx * scale, y + r * scale, scale, scale);
    }
  }
}

const K = '#1a1c2c'; // outline/eye dark

export const MON_SPRITES: Record<string, Sprite> = {
  sproutle: {
    pal: { g: '#4fb35a', G: '#2e7d3a', l: '#7ed957', d: '#1f5c2a', k: K, w: '#ffffff' },
    rows: [
      '................',
      '......ll........',
      '.....lGGl.......',
      '......GG........',
      '......dd........',
      '....gggggg......',
      '...gggggggg.....',
      '..gggkggkggg....',
      '..gggwggwggg....',
      '..gggggggggg....',
      '..ggg.kk.ggg....',
      '...gggggggg.....',
      '....gggggg......',
      '....gg..gg......',
      '...GG....GG.....',
      '................',
    ],
  },
  bramblore: {
    pal: { g: '#3f9c4d', G: '#2e7d3a', d: '#1f5c2a', p: '#e75480', k: K, w: '#ffffff' },
    rows: [
      '....d..p..d.....',
      '...dd.ppp.dd....',
      '....dgpppgd.....',
      '...ggggggggg....',
      '..ggggggggggg...',
      '.ggggkgggkgggg..',
      '.ggggwgggwgggg..',
      'dggggggggggggd..',
      '.gggg.kkk.ggg...',
      '.ggggggggggggg..',
      'd.ggggggggggg.d.',
      '..gggggggggggg..',
      '...ggggggggg....',
      '...ggg...ggg....',
      '..GGG.....GGG...',
      '................',
    ],
  },
  cindercub: {
    pal: { o: '#e8823a', O: '#c05f1e', f: '#ffd93b', F: '#ff6b35', c: '#f7d7b0', k: K, w: '#ffffff' },
    rows: [
      '................',
      '...oo....oo.....',
      '..oooo..oooo....',
      '..oooooooooo....',
      '..oookooko.f....',
      '..ooowoowoFf....',
      '..oooooooo.F....',
      '...ooccoo.......',
      '...occcco.......',
      '..oooccooo......',
      '.oooooooooo.....',
      '.oooooooooo.....',
      '.ooo.oo.ooo.....',
      '.OO..OO..OO.....',
      '................',
      '................',
    ],
  },
  emberuin: {
    pal: { o: '#d1541e', O: '#a03a10', f: '#ffd93b', F: '#ff6b35', c: '#f0c088', k: K, w: '#ffffff' },
    rows: [
      '...f..F..f......',
      '..fF.fFf.Ff.....',
      '..ooooooooo.....',
      '.ooooooooooo....',
      '.ookoooooko.....',
      '.oowoooowoo.....',
      '.ooooooooooo....',
      '..oocccoo..F....',
      '..occccco.Ff....',
      '.ooocccoooFf....',
      'ooooooooooo.f...',
      'ooooooooooo.....',
      'oooo.ooo.ooo....',
      'OOO..OO...OO....',
      '................',
      '................',
    ],
  },
  puddlefin: {
    pal: { b: '#5aa9e6', B: '#2d6fb5', s: '#e8c170', S: '#b5883f', c: '#bfe3ff', k: K, w: '#ffffff' },
    rows: [
      '................',
      '.....bbbb.......',
      '....bbbbbb......',
      '...bbkbbkbb.....',
      '...bbwbbwbb.....',
      '...bbbbbbbb.....',
      '....b.kk.b......',
      '..sssssssss.....',
      '.sssSSSSSsss....',
      '.ssSssssSSss....',
      '.sssSSSSSsss....',
      '..sssssssss.....',
      '...bb....bb.....',
      '..cBB....BBc....',
      '................',
      '................',
    ],
  },
  torrentle: {
    pal: { b: '#3d8fd1', B: '#215a8f', s: '#d9a94f', S: '#8f6a2a', c: '#bfe3ff', k: K, w: '#ffffff' },
    rows: [
      '......c.c.......',
      '.....ccccc......',
      '....bbbbbb......',
      '...bbkbbkbb.....',
      '...bbwbbwbb.....',
      '...bbbbbbbbb....',
      '....bbkkbb......',
      '.ssssssssssss...',
      'sssSSSSSSSSsss..',
      'ssSsssssssSSss..',
      'ssSsssssssSSss..',
      'sssSSSSSSSSsss..',
      '.ssssssssssss...',
      '..bbb.....bbb...',
      '.BBB.......BBB..',
      '................',
    ],
  },
  nibbit: {
    pal: { n: '#b08968', N: '#8a6547', c: '#e6ccb2', k: K, w: '#ffffff', t: '#ffffff' },
    rows: [
      '................',
      '................',
      '...nn....nn.....',
      '..nccn..nccn....',
      '..nnnnnnnnnn....',
      '..nnknnnnknn....',
      '..nnwnnnnwnn....',
      '..nnnnkknnnn....',
      '...nnnttnnn.....',
      '...nnnttnnn.....',
      '..nnncccnnnn....',
      '.nnnnnnnnnnnN...',
      '.nnnnnnnnnn.N...',
      '..nn.nn.nn.N....',
      '..NN.NN.NN......',
      '................',
    ],
  },
  fluffowl: {
    pal: { f: '#efe0c3', F: '#cbb086', o: '#f2a541', k: K, w: '#ffffff', y: '#ffd93b' },
    rows: [
      '................',
      '...f........f...',
      '..fff......fff..',
      '...ffffffffff...',
      '..ffffffffffff..',
      '..ffkkffffkkff..',
      '..ffkwffffkwff..',
      '..ffffyyyfffff..',
      'F.fffffyffffff.F',
      'FFffffffffffffFF',
      'F.ffffffffffff.F',
      '..ffFFFFFFFFff..',
      '...ffffffffff...',
      '....oo....oo....',
      '...ooo....ooo...',
      '................',
    ],
  },
  buzzler: {
    pal: { g: '#7a9e3b', G: '#55702a', h: '#3d5220', k: K, w: '#ffffff', l: '#b5cc6a' },
    rows: [
      '.......hh.......',
      '......hhhh......',
      '.......hh.......',
      '.......hh.......',
      '....gggggggg....',
      '...gggggggggg...',
      '..ggkggggggkgg..',
      '..ggwggggggwgg..',
      '.hgggggggggggh..',
      '.hglllggglllgh..',
      '.hglllggglllgh..',
      '..gggggggggggg..',
      '...gggggggggg...',
      '..h..h....h..h..',
      '.hh..hh..hh..hh.',
      '................',
    ],
  },
  cocoonet: {
    pal: { c: '#a8a4c4', C: '#75718f', v: '#d9d5ef', k: K, w: '#ffffff' },
    rows: [
      '................',
      '..vv........vv..',
      '.vvvv......vvvv.',
      '.vvvvv....vvvvv.',
      '.vvvcccccccvvvv.',
      '..vcccccccccvv..',
      '..ccckcccckcc...',
      '..cccwccccwcc...',
      '.vccccccccccvv..',
      '.vvccCCCCccvvv..',
      '..vcccccccccv...',
      '...ccCCCCCcc....',
      '....ccccccc.....',
      '.....CCCCC......',
      '......CCC.......',
      '................',
    ],
  },
  sparkit: {
    pal: { y: '#f5d442', Y: '#cfa91f', o: '#f2a541', k: K, w: '#ffffff', e: '#ff8c42' },
    rows: [
      '................',
      '...yy....yy.....',
      '..yoyy..yyoy....',
      '..yyyyyyyyyy....',
      '..yykyyyykyy....',
      '..yywyyyywyy....',
      '..yyyyykkyyy....',
      '...yyyyyyyy.....',
      '...yyyyyyyy..e..',
      '..yyyyyyyyy.ee..',
      '.yyyyyyyyyyee...',
      '.yyyyyyyyyye....',
      '.yyy.yy.yyy.e...',
      '.YY..YY..YY.....',
      '................',
      '................',
    ],
  },
  pebblit: {
    pal: { s: '#9a9a9a', S: '#6e6e6e', d: '#525252', k: K, w: '#ffffff' },
    rows: [
      '................',
      '................',
      '................',
      '.....ssssss.....',
      '....ssssssss....',
      '...ssssssssss...',
      '..ssskssssksss..',
      '..ssswsssswsss..',
      '..ssssssssssss..',
      '..ssss.kk.ssss..',
      '..SssssssssssS..',
      '..SSssssssssSS..',
      '...SSSssssSSS...',
      '....dSSSSSSd....',
      '................',
      '................',
    ],
  },
  bouldron: {
    pal: { s: '#8d8371', S: '#655d4e', d: '#463f33', k: K, w: '#ffffff' },
    rows: [
      '.....ssssss.....',
      '...ssssssssss...',
      '..ssssssssssss..',
      '.ssskssssssksss.',
      '.ssswssssssWsss.'.replace('W', 'w'),
      '.ssssssssssssss.',
      'ssssss.kkk.sssss',
      'ssssssssssssssss',
      'sSssssssssssssSs',
      'sSSssssssssssSSs',
      '.sSSSssssssSSSs.',
      'ss.SSSSSSSSSS.ss',
      'sss..dddddd..sss',
      '.SS..d....d..SS.',
      '.....dd..dd.....',
      '................',
    ],
  },
  mudlet: {
    pal: { m: '#a5754a', M: '#7d5432', c: '#d9b382', k: K, w: '#ffffff' },
    rows: [
      '................',
      '................',
      '....mm..........',
      '...mmmm...mm....',
      '..mmmmmmmmmmm...',
      '.mmkmmmmkmmmmm..',
      '.mmwmmmmwmmmmmm.',
      '.mmmmmmmmmmmmmM.',
      '.mmm.kkk.mmmmM..',
      '.mcccccccmmmm...',
      '..mcccccmmmmM...',
      '...mmmmmmmmM....',
      '....mm...mm.....',
      '...MM....MM.....',
      '................',
      '................',
    ],
  },
  floazy: {
    pal: { b: '#7fc8f8', B: '#4a9fd8', y: '#f2c14e', c: '#e8f4fd', k: K, w: '#ffffff' },
    rows: [
      '................',
      '.....bbbb.......',
      '....bbbbbb......',
      '...bbkbbbbb.....',
      '...bbwbbbbb.....',
      '...bbbyyyy......',
      '....bbbyy.......',
      '....bbb.........',
      '...bbbbbbbbbb...',
      '..bbbbbbbbbbbb..',
      '..cbbbbbbbbbbc..',
      '..ccbbbbbbbbcc..',
      '...cccccccccc...',
      '....ccc..ccc....',
      '................',
      '................',
    ],
  },
  psywisp: {
    pal: { p: '#d98cc4', P: '#a85a96', v: '#f0c4e4', k: K, w: '#ffffff' },
    rows: [
      '................',
      '......pppp......',
      '....pppppppp....',
      '...pppppppppp...',
      '...ppkppppkpp...',
      '...ppwppppwpp...',
      '..pppppppppppp..',
      '..ppp.pkkp.ppp..',
      '..pppppppppppp..',
      '.vppppppppppppv.',
      '.vpppppppppppv..',
      '..vpppvpppvpv...',
      '...vpv.vpv.v....',
      '....v...v.......',
      '................',
      '................',
    ],
  },
  thistling: {
    pal: { g: '#6ba644', G: '#487a2c', p: '#c77dba', k: K, w: '#ffffff', d: '#2e5220' },
    rows: [
      '....d..p..d.....',
      '.....d.p.d......',
      '....pppppp......',
      '...ggggggggg....',
      '..gggggggggg....',
      '..ggkggggkgg....',
      '..ggwggggwgg....',
      '.dggggggggggd...',
      '..ggg.kk.ggg....',
      '..gggggggggg....',
      '.d.gggggggg.d...',
      '....gggggg......',
      '....gg..gg......',
      '...GG....GG.....',
      '................',
      '................',
    ],
  },
  gustling: {
    pal: { c: '#e8ecf4', C: '#b8c4d8', s: '#8fa3c0', k: K, w: '#ffffff' },
    rows: [
      '................',
      '.....ccccc......',
      '....ccccccc.....',
      '...cckccccc.....',
      '...ccwccccc.....',
      '...cccssss......',
      '..ccccccccccc...',
      '.ccccccccccccc..',
      'Ccccccccccccccc.',
      'CCccccccccccccC.',
      '.CCcccccccccCC..',
      '..CCCcccccCCC...',
      '....CCCCCCC.....',
      '......CCC.......',
      '................',
      '................',
    ],
  },
  zapwing: {
    pal: { y: '#f5d442', Y: '#cfa91f', b: '#4a6fd8', k: K, w: '#ffffff', o: '#f2a541' },
    rows: [
      '.......yy.......',
      '......yyyy......',
      '.....yykyyy.....',
      '.....yywyyy.....',
      '.....yyyooo.....',
      '..b..yyyyy......',
      '.bb.yyyyyyy.bb..',
      '.bbyyyyyyyyybb..',
      'bbbyyyyyyyyybbb.',
      '.bbyyyyyyyyybb..',
      '..byyyyyyyyyb...',
      '...yyyyyyyyy....',
      '....yyyyyyy.....',
      '.....oo.oo......',
      '....ooo.ooo.....',
      '................',
    ],
  },
  flarat: {
    pal: { r: '#d1543a', R: '#a03a24', c: '#f0b8a0', f: '#ffd93b', F: '#ff6b35', k: K, w: '#ffffff' },
    rows: [
      '................',
      '...rr....rr.....',
      '..rccr..rccr....',
      '..rrrrrrrrrr....',
      '..rrkrrrrkrr....',
      '..rrwrrrrwrr....',
      '..rrrrkkrrrr....',
      '...rrrrrrrr.....',
      '...rrrrrrrr..f..',
      '..rrrrrrrrr.fFf.',
      '.rrrrrrrrrrR.F..',
      '.rrrrrrrrrrR....',
      '.rrr.rr.rrrR....',
      '.RR..RR..RR.....',
      '................',
      '................',
    ],
  },
  nibblex: {
    pal: { n: '#a07840', N: '#7a5a28', c: '#e8d0a8', f: '#ffffff', k: K, w: '#ffffff' },
    rows: [
      '................',
      '...nnn....nnn...',
      '..nnnnn..nnnnn..',
      '..nnnnnnnnnnnn..',
      '.nnnnnnnnnnnnnn.',
      '.nnknnnnnnnnknn.',
      '.nnwnnnnnnnnwnn.',
      '.nnnnnnkknnnnnn.',
      'nnnnnnnnnnnnnnnn',
      '.ncnnffffffnncn.',
      '.ncnnffffffnncn.',
      '.nnnnnnnnnnnnnn.',
      '..nnnnnnnnnnnn..',
      '...nnn....nnn...',
      '..NNN......NNN..',
      '................',
    ],
  },
  howlette: {
    pal: { h: '#8a6a3a', H: '#6a4e28', c: '#f0e0c0', o: '#f2a541', k: K, w: '#ffffff' },
    rows: [
      '................',
      '..hh........hh..',
      '..hhhhhhhhhhhh..',
      '.hhhhhhhhhhhhhh.',
      '.hcchhhhhhhhcch.',
      '.hhhkhhhhhhkhhh.',
      '.hhhwhhhhhhwhhh.',
      '.hhhhhhoohhhhhh.',
      '.hhhhhhhhhhhhhh.',
      'HhhhhhhhhhhhhhhH',
      'HHhhhhhhhhhhhhHH',
      '.HHhhhhhhhhhhHH.',
      '..hhhhhhhhhhhh..',
      '...oo......oo...',
      '................',
      '................',
    ],
  },
  voltkat: {
    pal: { y: '#f5d442', Y: '#cfa91f', b: '#33303a', k: K, w: '#ffffff' },
    rows: [
      '................',
      '...yy......yy...',
      '..yyyy....yyyy..',
      '..yyyyyyyyyyyy..',
      '.yyyyyyyyyyyyyy.',
      '.yykyyyyyyyykyy.',
      '.yywyyyyyyyywyy.',
      '.yyyyyykkyyyyyy.',
      'ybyyyyyyyyyyybyy',
      '.yyyyyyyyyyyyyy.',
      '.ybyyyyyyyyyyby.',
      '..yyyyyyyyyyyy..',
      '...yyyy..yyyy...',
      '..YYyy....yyYY..',
      '............bb..',
      '...........bbb..',
    ],
  },
  driftail: {
    pal: { c: '#e8ecf4', b: '#4a8fd8', k: K, w: '#ffffff' },
    rows: [
      '................',
      '......cc........',
      '.....cccc.......',
      '....cccccc......',
      '...cckccccc.....',
      '...ccwcccccc....',
      '...ccccccccc....',
      '..bcccccccccb...',
      '.bbbcccccccbbb..',
      'bbbbcccccccbbbb.',
      '.bbb.ccccc.bbb..',
      '.....ccccc......',
      '....bbccbb......',
      '...bb....bb.....',
      '..bb......bb....',
      '..b........b....',
    ],
  },
  somnara: {
    pal: { p: '#b48ad8', l: '#e0c8f8', y: '#ffd93b', k: K, w: '#ffffff' },
    rows: [
      '.......y........',
      '......yyy.......',
      '....ppppppp.....',
      '...ppppppppp....',
      '..ppkpppppkpp...',
      '..ppwpppppwpp...',
      '..ppppppppppp...',
      '.ppppppppppppp..',
      '.ppplppppplppp..',
      '.pppplppplpppp..',
      '..ppppppppppp...',
      '...ppppppppp....',
      '....ppp.ppp.....',
      '.....pp..pp.....',
      '.....p....p.....',
      '................',
    ],
  },
  mimew: {
    pal: { p: '#e8a0c8', P: '#c878a8', k: K, w: '#ffffff' },
    rows: [
      '................',
      '.....pp.........',
      '....pppp........',
      '...ppppppp......',
      '..pppppppppp....',
      '.pppppppppppp...',
      '.ppkppppppkpp...',
      '.pppppppppppp...',
      'ppppppkkkkppppp.',
      'pppppppppppppppp',
      '.pppppppppppppp.',
      'PppppppppppppppP',
      'PPppppppppppppPP',
      '.PPPPPPPPPPPPPP.',
      '................',
      '................',
    ],
  },
};

// ---- People (overworld + battle back sprite) ----

function person(hair: string, shirt: string, pants: string, skin = '#f0c8a0'): Sprite {
  return {
    pal: { h: hair, s: shirt, p: pants, f: skin, k: K, o: '#4a3020' },
    rows: [
      '................',
      '.....hhhhhh.....',
      '....hhhhhhhh....',
      '....hhhhhhhh....',
      '....hffffffh....',
      '....ffkffkff....',
      '.....ffffff.....',
      '.....f.kk.f.....',
      '....ssssssss....',
      '...fsssssssssf..',
      '...fsssssssssf..',
      '....ssssssss....',
      '.....pppppp.....',
      '.....pp..pp.....',
      '.....pp..pp.....',
      '.....oo..oo.....',
    ],
  };
}

export const PEOPLE: Record<string, Sprite> = {
  player: person('#c0392b', '#2d6fb5', '#333c57'),
  rival: person('#3a5fc0', '#7d3ac0', '#2e2e3e'),
  professor: person('#8a8a8a', '#f0f0f0', '#6e5a3a'),
  nurse: person('#e879b0', '#ffffff', '#e879b0'),
  clerk: person('#4a3020', '#3a7ca5', '#333c57'),
  villager1: person('#6e5a3a', '#7a9e3b', '#8a6547'),
  villager2: person('#2e2e3e', '#d98c3a', '#3a5fc0'),
  hiker: person('#4a3020', '#8f6a2a', '#655d4e'),
  bugcatcher: person('#d9a94f', '#f5f0d0', '#3a7ca5'),
  lass: person('#d98c3a', '#e75480', '#3a5fc0'),
  gymleader: person('#8f6a2a', '#c05f1e', '#463f33'),
};

export function monSprite(key: string): Sprite {
  return MON_SPRITES[key] ?? MON_SPRITES.nibbit;
}
